### ISSUE TITLE
Ability to use TaskProvider (+ tasks that output files and directories) when adding artifact to a configuration

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#10960]
### Expected Behavior

Gradle should allow using `TaskProvider`:

try the following with `./gradlew outgoingVariants`

```kotlin
val srcLicense by configurations.creating {
    isCanBeResolved = false
    isCanBeConsumed = true
}

val srcLicenseDir by tasks.registering(Sync::class) {
    into("$buildDir/$name")
    dependencyLicenses(srcLicenseSpec)
}

(artifacts) {
    srcLicense(srcLicenseDir)
    // The below fails as well
    // add("srcLicense", srcLicenseDir)
    // This works (~Gradle 5.6 and 6.0):
    // add(srcLicense.name, srcLicenseDir.get().destinationDir) {
    //     builtBy(srcLicenseDir)
    // }
}
```

### Current Behavior

`artifacts` fails when it sees a `TaskProvider` :-/

```
Caused by: org.gradle.api.InvalidUserDataException: Cannot convert provided value (task ':src:licenses:srcLicenseDir') to a file.
        at org.gradle.api.internal.artifacts.dsl.LazyPublishArtifact.getDelegate(LazyPublishArtifact.java:91)
        at org.gradle.api.internal.artifacts.dsl.LazyPublishArtifact.getType(LazyPublishArtifact.java:62)
        at org.gradle.api.internal.artifacts.publish.DecoratingPublishArtifact.getType(DecoratingPublishArtifact.java:60)
        at org.gradle.api.internal.artifacts.publish.DecoratingPublishArtifact_Decorated.getType(Unknown Source)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet$DefaultArtifactProvider.getOrNull(DefaultArtifactPublicationSet.java:91)
        at org.gradle.api.internal.plugins.DefaultArtifactPublicationSet$DefaultArtifactProvider.getOrNull(DefaultArtifactPublicationSet.java:49)
        at org.gradle.api.internal.provider.AbstractReadOnlyProvider.get(AbstractReadOnlyProvider.java:27)
        at org.gradle.api.internal.provider.Collectors$ElementsFromCollectionProvider.collectInto(Collectors.java:235)
        at org.gradle.api.internal.provider.Collectors$TypedCollector.collectInto(Collectors.java:371)
        at org.gradle.api.internal.collections.AbstractIterationOrderRetainingElementSource$Element.realize(AbstractIterationOrderRetainingElementSource.java:323)
        at org.gradle.api.internal.collections.AbstractIterationOrderRetainingElementSource.realizePending(AbstractIterationOrderRetainingElementSource.java:138)
        at org.gradle.api.internal.DefaultDomainObjectCollection.addEagerAction(DefaultDomainObjectCollection.java:226)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:144)
        at org.gradle.api.internal.CompositeDomainObjectSet.addCollection(CompositeDomainObjectSet.java:108)
        at org.gradle.api.internal.CompositeDomainObjectSet.create(CompositeDomainObjectSet.java:56)
        at org.gradle.api.internal.collections.DefaultDomainObjectCollectionFactory.newDomainObjectSet(DefaultDomainObjectCollectionFactory.java:77)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.initAllArtifacts(DefaultConfiguration.java:829)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getAllArtifacts(DefaultConfiguration.java:811)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getAllArtifacts(Unknown Source)
        at org.gradle.api.plugins.BasePlugin$4.execute(BasePlugin.java:193)
        at org.gradle.api.plugins.BasePlugin$4.execute(BasePlugin.java:190)
        at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:42)
        at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:42)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:94)
        at org.gradle.internal.ImmutableActionSet$SetWithManyActions.execute(ImmutableActionSet.java:329)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:264)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:112)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:258)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:942)
        ... 162 more
```

Note: If I use `add(srcLicense.name, srcLicenseDir.get())`, then the message is a bit different:

```
org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert the provided notation to an object of type ConfigurablePublishArtifact: task ':src:licenses:srcLicenseDir'.
The following types/formats are supported:
  - Instances of ConfigurablePublishArtifact.
  - Instances of PublishArtifact.
  - Instances of AbstractArchiveTask, for example jar.
  - Instances of Provider<RegularFile>.
  - Instances of Provider<Directory>.
  - Instances of Provider<File>.
  - Instances of RegularFile.
  - Instances of Directory.
  - Instances of File.
  - Maps with 'file' key
        at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:57)
        at org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler.pushArtifact(DefaultArtifactHandler.java:55)
        at org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler.add(DefaultArtifactHandler.java:68)
        at Build_gradle$3.execute(build.gradle.kts:232)
        at Build_gradle$3.execute(build.gradle.kts:31)
        at org.gradle.api.internal.project.DefaultProject.artifacts(DefaultProject.java:1202)
        at org.gradle.kotlin.dsl.support.delegates.ProjectDelegate.artifacts(ProjectDelegate.kt:248)
        at Build_gradle.<init>(build.gradle.kts:225)
        at Program.execute(Unknown Source)
```

### Context

I'm trying to share artifacts between Gradle modules, and the current DSL is not that intuitive.
Just in case, I've a [module that lists licensing information](https://github.com/apache/jmeter/blob/ca26f5f26703b77eb3e33b4a890215c79908267d/src/licenses/build.gradle.kts). It generates `LICENSE` file which I want to use in other modules.

**Comment by melix** [comment]
@vlsi do you mind sharing a simple build which reproduces this problem? I'm working on something related but it looks that this issue is already fixed, but I may not reproduce it correctly.

**Comment by jjohannes** [comment]
I think in general this works for `Provider<ArchiveTask>`. It definitely works if you use the "alternative" API: `configuration.outgoing.artifact(...)` 

I think this is more about supporting more task types (directly or through provider).

When we talk about the Sync/Copy task, the following is related and maybe these things could be addressed together (if it makes sense): https://github.com/gradle/gradle/issues/13275

**Comment by melix** [comment]
I did try with a `Sync` task with the notation above and it works.

**Comment by jjohannes** [comment]
Interesting. I didn't know that. Thanks.

**Comment by vlsi** [comment]
@melix , here's the reproducer: https://github.com/vlsi/gradle-issue-reproducers/pull/3

It looks like the issue is still there for all Gradle versions including nightly (see [GitHub Actions](https://github.com/vlsi/gradle-issue-reproducers/pull/3/checks) )

**Comment by jjohannes** [comment]
So forget what I wrote. The initial report is right. And I think https://github.com/gradle/gradle/pull/13505 could solve this problem.

**Comment by melix** [comment]
Thanks @vlsi , will take a look!

**Comment by melix** [comment]
This works with the changes in #13505
