### ISSUE TITLE
Gradle 6.0 generates incorrect versions for Kotlin multiplatform projects when publishing to Bintray

### ISSUE THREAD

**Issue by serebit** [gradle/gradle#11412]
### Expected Behavior
When publishing a Kotlin multiplatform project to Bintray using the `maven-publish` plugin, only one version should be created, that being the project's version. All artifacts should then be published to that version in Bintray. This was the case in Gradle versions before 6.0. In practice, for a package `logkat` with two platform targets (JVM and linux-x64) and a version of `0.5.0`, the correct Bintray output would be:
![image](https://user-images.githubusercontent.com/12981608/69076352-45c4ec80-0a01-11ea-8d52-4c3db2c3761c.png)

### Current Behavior
In Gradle 6.0, a version is created for the project's version, but then versions are created for each artifact. In practice, for a package `logkat` with two platform targets (JVM and linux-x64) and a version of `0.5.0`, the putput for Gradle 6.0 is:
![image](https://user-images.githubusercontent.com/12981608/69076595-d3a0d780-0a01-11ea-9b75-c424adce5a28.png)

### Context
This issue happens with Gradle 6.0 only. All previous versions do not have this issue. The "correct" output is from Gradle 5.6.3.

### Steps to Reproduce 
My project at https://gitlab.com/serebit/logkat currently has a Gradle 6.0 wrapper, and generates the above when publishing to its "snapshot" repository.

### Your Environment
This happens both on my Linux desktop and in GitLab CI, using OpenJDK 8 or OpenJDK 11.

**Comment by ljacomet** [comment]
I am not a specialist of Bintray but the version concept seems to be something they own, it is for sure not something Gradle defines, aside from the `project.version` property.

From my understanding, without using the [Bintray plugin](https://github.com/bintray/gradle-bintray-plugin), there is no guarantee that only one version will be created.

* Are all the files at the expected location on the repository?
* Any chance you can capture the different calls to upload?

Sadly I cannot even produce a full publication on a local repository as I have some failures when attempting to do so, since I do not run on Linux.

But my initial guess is that since we changed Maven uploads to be parallel (#8950), you no longer have the single version guarantee.

Could you try with Gradle 5.6.4?

**Comment by serebit** [comment]
I can in a bit. For what it's worth, publishing to a local repository does not have this effect, only to Bintray as far as I know. 

The "correct" screenshot was from logkat with Gradle 5.6.3. I can check with 5.6.4 if there were any changes between the two.

**Comment by serebit** [comment]
Just checked with a couple more versions. Gradle 5.6.3 and 5.6.4 do not suffer from this problem. Gradle 6.0-rc-1 and 6.0 both suffer from this problem.

**Comment by ljacomet** [comment]
Can you give a link of the problematic snapshot release?
I still believe what's uploaded is correct, it just ends up messing the build / version concept of the Bintray UI.

**Comment by serebit** [comment]
Sure, one minute. I'll upload a version with 5.6.4 and a version with 6.0 for comparison. On the latter point, I'd be inclined to agree, if Gradle didn't fail to resolve the correct version from Bintray (`0.5.0` in this case). That's actually why I started looking into this in the first place.

**Comment by serebit** [comment]
[Here is the Bintray repository containing the test publications.](https://bintray.com/serebit/snapshot/logkat) Supplementary information:
- The following "versions" were created with commit 1c96766: `gradle-5.6.4`
- The following "versions" were created with commit 9f7e3c8: `gradle-6.0`, `logkat-jvm`, `logkat`, `logkat-linuxx64`, `logkat-metadata`

**Comment by ljacomet** [comment]
So I browsed the uploaded files, from `maven-metadata.xml` to the specific artifacts of `logkat`, including `.pom` and `.module`. There are no _unexpected_ differences between `gradle-5.6.4` and `gradle-6.0` under https://dl.bintray.com/serebit/snapshot/com/serebit/logkat/

However one difference is that Gradle now uploads `.sha256` and `.sha512` files, including for the `maven-metadata.xml`. I believe these checksum files for `maven-metadata.xml` are causing the confusion for Bintray.

Could you try a Gradle 6.0.1 upload with the following property set:
>Since 6.0.1, if your external repository doesn't support SHA256 and/or SHA512 checksums, it is possible to disable upload of those checksums:
>
> * add -Dorg.gradle.internal.publish.checksums.insecure=true to the CLI or
> * add systemProp.org.gradle.internal.publish.checksums.insecure=true to your gradle.properties file

**Comment by serebit** [comment]
Just tested with Gradle 6.0.1 and the given property, and that does indeed seem to fix the problem. Odd that just adding additional checksums causes Bintray to completely misinterpret uploaded files, but that's not a Gradle problem, so I'll take it up with Jfrog. Thanks for the fix!

**Comment by ljacomet** [comment]
Great, thanks for confirming what I suspected.

Two things:
* Please link the JFrog issue here once you open it, so we can follow up on it.
* You could decide to keep producing these files and effectively _ignore_ all unexpected versions. When looking at the `gradle-6.0` version in your example, it properly references all the files that are mandatory for your publication to be valid.

**Comment by serebit** [comment]
JFrog doesn't have a public issue tracker as far as I know, so I used their contact form on their support page. I will update here when (or if) they get back to me, though.

On your latter point with ignoring all unexpected versions, I'd be fine with that for the snapshot releases, but for releases to my public repository that mirrors to jcenter, I'd rather not confuse anyone trying to find the latest version. I'm fine with waiting until this is resolved to start including SHA hashes in releases.

**Comment by martinbonnin** [comment]
I can confirm this happens on JVM projects too. This happened to me when uploading the sha512 checksum. No idea why, I'll ping jfrog support as well.

**Comment by ljacomet** [comment]
Did you ever hear from JFrog on this?

My understanding is that JFrog considers the `*.sha512` files to be artifacts instead of checksums related to real artifacts.
There is not much that can be done on the Gradle side for this.

**Comment by martinbonnin** [comment]
> Did you ever hear from JFrog on this?

Yes, I got an answer that they were looking into it, without much more details though. Let me ask again.

> There is not much that can be done on the Gradle side for this.

Agreed, it's a jfrog thing. I would kept this ticket open though as reference.

**Comment by hemanthsridhar** [comment]
Whoever is facing this concern, 
just disable the sha512 and sha256 checksum generation

by adding 

systemProp.org.gradle.internal.publish.checksums.insecure=true

in your gradle.properties

**Comment by LouisCAD** [comment]
Is there any security or reliability issue that can arise by disabling sha512 and sha256 checksum generation?

**Comment by hemanthsridhar** [comment]
@LouisCAD

I doubt, but Bintray and Maven Central are not handling them. (Not just Bintray)

**Comment by animusnull** [comment]
Not sure where to add this. But I'm seeing the same thing with gitlab packages. 

Sonatype nexus and artifactory was working locally via docker test instances. I moved to a maven repo hosted via appengine and it's working fine.

I created an upstream isssues with gitlab
https://gitlab.com/gitlab-org/gitlab/-/issues/212764

**Comment by hemanthsridhar** [comment]
@animusnull All these guys need to start developing a feature to handle sha512 and sha256. Till then, we all have to just **-Dorg.gradle.internal.publish.checksums.insecure**=true and wait

**Comment by SalomonBrys** [comment]
Btw, it looks like a third solution is to put:

```
System.setProperty("org.gradle.internal.publish.checksums.insecure", "true")
```

in the file `settings.gradle.kts`

**Comment by serebit** [comment]
Surprised this still isn't fixed after almost a year. Wonder what Jfrog is doing instead of resolving issues with Bintray :p

**Comment by LouisCAD** [comment]
Did anyone reach their support?

**Comment by martinbonnin** [comment]
@LouisCAD [yes](https://github.com/gradle/gradle/issues/11412#issuecomment-587499854)

The latest news I have was end of March 2020. They gave me a ticket number (JBT-3035), which is internal so if anyone from Bintray is reading this, they might be able to get a bit more info.

**Comment by ljacomet** [comment]
Can anyone confirm if the issue has been fixed on the Bintray side?

**Comment by msink** [comment]
For me it broke recently even worse - now even with above-mentioned workaround build failed:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':libui:publishKotlinMultiplatformPublicationToMavenRepository'.
> Failed to publish publication 'kotlinMultiplatform' to repository 'maven'
   > Could not PUT 'https://api.bintray.com/maven/msink/kotlin-dev/libui/;publish=0;override=1/com/github/msink/libui/0.1.9-dev/libui-0.1.9-dev.pom'. Received status code 401 from server: Unauthorized
```
A month ago it worked, and nothing has changed on my side.

**Comment by LouisCAD** [comment]
Did you reach Bintray support for that new issue @msink?

**Comment by msink** [comment]
Well, no - but seems to be false alarm - it does not work only for CI build started by PR, and is expected:

> However, secure variables are not decoded during Pull Request builds which prevents someone from submitting PR with malicious build script displaying those variables. In more controlled environment through with a trusted team and private GitHub repositories there is an option on General tab of project settings to allow secure variables for PRs.

But IIRC it worked before, maybe recent "security fix" on CI server.
Anyway unrelated to bintray, sorry.

**Comment by msink** [comment]
@ljacomet yes - for me now it works as expected:
https://dl.bintray.com/msink/kotlin-dev/com/github/msink/libui-windows64/0.1.9-dev/
```
libui-windows64-0.1.9-dev-cinterop-libui.klib
libui-windows64-0.1.9-dev-cinterop-libui.klib.md5
libui-windows64-0.1.9-dev-cinterop-libui.klib.sha512
libui-windows64-0.1.9-dev-sources.jar
libui-windows64-0.1.9-dev-sources.jar.md5
libui-windows64-0.1.9-dev-sources.jar.sha512
libui-windows64-0.1.9-dev.klib
libui-windows64-0.1.9-dev.klib.md5
libui-windows64-0.1.9-dev.klib.sha512
libui-windows64-0.1.9-dev.module
libui-windows64-0.1.9-dev.module.md5
libui-windows64-0.1.9-dev.module.sha512
libui-windows64-0.1.9-dev.pom
libui-windows64-0.1.9-dev.pom.md5
libui-windows64-0.1.9-dev.pom.sha512
```

Seems to be fixed on bintray side.

**Comment by joffrey-bion** [comment]
Looks like the same issue was fixed on Maven Central side as well:
https://issues.sonatype.org/browse/MVNCENTRAL-5276

Should this issue be closed, or is there still something missing?
This is to know if I should keep the flag `systemProp.org.gradle.internal.publish.checksums.insecure=true` on for now.

**Comment by serebit** [comment]
Gonna close this, since it appears to be fixed for both Bintray and Maven Central. Feel free to comment if you're still seeing this issue.

**Comment by ljacomet** [comment]
Thank you folks for following up!

**Comment by martinbonnin** [comment]
Looks like the problem is still happening for us on bintray: 

<img width="639" alt="Screenshot 2020-11-30 at 10 53 43" src="https://user-images.githubusercontent.com/3974977/100594770-65703f80-32fa-11eb-82dd-6c75830fc12a.png">

@msink I would have expected the fix to be 100% on bintray side but maybe we'll need a more recent Gradle? Which version of Gradle did you use?

**Comment by msink** [comment]
@martinbonnin tested on Gradle 6.6.1
But it's Kotlin/Native project: https://github.com/msink/kotlin-libui/tree/publish-checksums
Maybe plain JVM Java or Kotlin works differently...

**Comment by fluidsonic** [comment]
Also not working for me with Gradle 6.7.1.
Kotlin/Native artifact names are used as version numbers.

**Comment by serebit** [comment]
gg bintray

**Comment by msink** [comment]
Well, tried again and looked more precisely - and yes, after running Gradle "publish" task - extra versions for each artifact still are created in Bintray UI page (https://bintray.com/msink/kotlin-dev/libui)
But on download page (https://dl.bintray.com/msink/kotlin-dev/com/github/msink/) artifacts are in right places.
IIRC year ago both "bintray.com" and "dl.bintray.com" were broken?

**Comment by serebit** [comment]
It would seem that JFrog elected to shut down JCenter and Bintray rather than fix the issue. As Bintray is no longer relevant, I will be closing this issue.
