### ISSUE TITLE
Redundant whitespace when executing "gradle --version" (windows only)

### ISSUE THREAD

**Issue by nerro** [gradle/gradle#1285]
I noticed that this bug exists only if I execute `gradle --version` on Windows. The first line (before Gradle word) with `----` has a whitespace at begin of the line ` ----`.

### Expected Behavior
```bash
$ gradlew --version
------------------------------------------------------------
Gradle <version>
------------------------------------------------------------
```

### Current Behavior
```bash
 ------------------------------------------------------------
Gradle 3.3
------------------------------------------------------------

Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_73 (Oracle Corporation 25.73-b02)
OS:           Windows 7 6.1 amd64
```

Perhaps better with screenshot
![redundant_whitespace](https://cloud.githubusercontent.com/assets/5961772/22509918/46c0e3a4-e890-11e6-9df5-8ed903d5c161.png)

### Context
On my Linux CI server it looks good with the same version of Gradle. And first time I saw this in 3.2 release (I think).

### Steps to Reproduce (for bugs)
1. Open cmd.exe on Windows
2. Execute `gradlew --version`

**Comment by lacasseio** [comment]
Good eyes @nerro! Would you mind looking into it to find the cause and provide a PR? As this is purely cosmetic, this issue would be extremely low on our priority list. Your help on this issue would be greatly appreciated.

**Comment by nerro** [comment]
Sure, it's nice-to-have :smile:

Shame on me, I looked already in [CommandLineActionFactory.java#154](https://github.com/gradle/gradle/blob/master/subprojects/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionFactory.java#L154), but found nothing. Could it be a start *bat script? Because there is no issue for Linux systems.

**Comment by lacasseio** [comment]
I suspect an issue in [`AnsiConsole`](https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/logging/console/AnsiConsole.java). However, it may actually be in [JAnsi](https://github.com/fusesource/jansi) which have really specific code for Windows. We are currently changing lots of code in `AnsiConsole`. You could build [`parallel-console` branch from source](https://github.com/gradle/gradle/tree/parallel-console) and give it a try on Windows to see if we fixed the issue by mistake. If our recent work didn't fix the issue, you will have to dig around the `logging` project and `jansi` to find the problem. Thanks for helping out.

**Comment by nerro** [comment]
Thanks for tips. I will keep you informed about my progress.

**Comment by nerro** [comment]
Small update from my side. The issue still exists in `parallel-console` branch. I'm "digging" further.
```bash
$ ./gradle --version
 ------------------------------------------------------------
Gradle 3.5-20170209144620+0000
------------------------------------------------------------

Build time:   2017-02-09 14:46:20 UTC
Revision:     a8a777ceffaadac143fcacf89ed4112ea72675cf

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_73 (Oracle Corporation 25.73-b02)
OS:           Windows 7 6.1 amd64
```

**Comment by fejese** [comment]
I've done a little digging, not sure how much it will help, but here it is.

In ``org.gradle.launcher.cli.CommandLineActionFactory.ShowVersionAction.run()`` there's this line:

    sb.append(":\n:------------------------------------------------------------\nGradle ");

The two colons I've added for testing and this is the result:

    C:\gradle-tmp>bin\gradle.bat --version
    :
      :------------------------------------------------------------
    Gradle 3.5-snapshot-1
    ------------------------------------------------------------

Notice that now there're 2 spaces.
It does not happen though when the output is redirected to a file.

It looks like that the windows console does not handle well the first ``\n`` line break whereas has no problem with succeeding ones.

However on windows, windows style EOL should be used I guess. It looks like that using `%n` instead of `\n` in combination with `String.format()` the issue is gone.

**Comment by lacasseio** [comment]
Great work @fejese and well-written explanation. Also thanks @nerro for getting the ball rolling on this and opening an issue.

**Comment by nerro** [comment]
:+1:  for @fejese. I hope my GitLab logs will look pretty again.

**Comment by fejese** [comment]
@nerro, I hope so too :)
@lacasseio, thanks, I'll work on the integration test as @bmuschko requested

**Comment by bmuschko** [comment]
Based on the commit history it looks to me as if the change made into 3.5 already in February. Closing the issue.
