### ISSUE TITLE
Gradlew blocks having negative ms (miliseconds) as process-time

### ISSUE THREAD

**Issue by enexusde** [gradle/gradle#14439]
I like to run ./gradlew bootRun in a project that last week worked fine.

### Expected Behavior
Build and run the project.

### Current Behavior
Not building and not working, process still alive counting "down" time.

### Context
I did not changed the version since last week.
--version gives me:
```
xxx@xxx:~/git/xxx/backend$ ./gradlew --version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8 (Oracle Corporation 11.0.8+10-LTS)
OS:           Linux 5.4.0-45-generic amd64
```

### Steps to Reproduce 
Not sure how to reproduce since no experiences exists with gradle.

### Your Environment
Unknown what is of interrest. Linux 64, Spring-boot-project.

**Comment by enexusde** [comment]
```
xxx@xxx:~/git/xxx/backend$ ./gradlew bootRun
<=========----> 75% EXECUTING [-6831343ms]
> :bootRun
^Cxxx@xxx:~/git/xxx/backend$ ./gradlew --version

```

**Comment by big-guy** [comment]
This is weird.  Does this happen every time for you now?

**Comment by enexusde** [comment]
Yes. Was a blocker, I fixed it by change from Linux to WindowsXP.

**Comment by jjohannes** [comment]
This looks like it was an issue with the local environment. Closing due to missing reproducer.

**Comment by javakrieg** [comment]
> This looks like it was an issue with the local environment. Closing due to missing reproducer.

I am currently experiencing this issue.  I am using gradle 6.8.1 and I am on a Linux system.  Everything was working fine until I did a sudo command to update the time on the system.

sudo date +%T -s "09:56:02"

After that, I get a huge negative countdown on every gradlew call.  Is there something I need to clean out on the system (something in the .gradle dir perhaps?) to fix this issue?

platform-> gradlew startContainers
<========-----> 66% EXECUTING [-36879694ms]

**Comment by jjohannes** [comment]
I would assume that this is an "in memory caching" issue. Stopping the daemon process would fix it then - `gradlew --stop`.

**Comment by javakrieg** [comment]
I removed the .gradle directory (didn't fix the issue) and then rebooted the Linux VM.  The reboot fixed the issue.  Didn't get to try your daemon idea.

**Comment by TheMatt2** [comment]
Ran into this issue. Deleting the `.gradle` directory and rebooting solved it.
Windows 11

```
------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (Eclipse Adoptium 17.0.6+10)
OS:           Windows 11 10.0 amd64
```

**Comment by rwtrench** [comment]
If it's useful, I replicated this issue recently by:
- run some command (example ./gradlew bootrun)
- change system clock timezone
- stop running thing 1
-  run some command again

The solution @jjohannes suggested of stopping and starting the daemon resolved it, but just wanted to put this here for how to re-create the issue.

**Comment by ov7a** [comment]
@rwtrench, Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before a fix is made.

**Comment by nguyenjulian** [comment]
> I would assume that this is an "in memory caching" issue. Stopping the daemon process would fix it then - `gradlew --stop`.

Resolved issue for me. Thanks!

**Comment by danieladams456** [comment]
> I would assume that this is an "in memory caching" issue. Stopping the daemon process would fix it then - gradlew --stop.

Same for me, hit this when upgrading from `8.1.1` to `8.2.1`.  `8.1.1` to `8.2` worked.  I thought it was something with the `8.2` to `8.2.1`, but this fixed it.

I assumed everything would get cleared/restarted when changing gradlew versions, but seems like it doesn't necessarily?

**Comment by enexusde** [comment]
Hm, I have an airborne server who swiches timezones frequently. Neither disable timezone support nor killing the gradlew deamon is an option there. I will try to use a docker-container for build or move forward to mvnd.
