### ISSUE TITLE
Impossible to run modular program with 7.0-milestone-2. Working with 6.8

### ISSUE THREAD

**Issue by bjonnh** [gradle/gradle#16541]
### Expected Behavior
For it to build like in Gradle 6.8.

### Current Behavior
The build breaks saying:

> Task :run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Module demo not found

### Context

I was trying Gradle 7.0 with my project, and it stopped running using the application plugin (it was working well in 6.8).
However, the jlinked version works properly (using org.beryx.jlink).

### Steps to Reproduce
Clone this repository:
https://github.com/bjonnh/2021_modules_unnamed_error

and run it (it will use 7.0-milestone-2) with ./gradlew run

Change the gradle version to 6.8 (in gradle/wrapper/gradle-wrapper.properties), and it will run.

### Your Environment

Build scan URL: https://scans.gradle.com/s/qjgrdgnliflaw

**Comment by ljacomet** [comment]
Could you try with milestone 3 and report?

**Comment by jjohannes** [comment]
@bjonnh the reproducer does not have module support turned on - `java.modularity.inferModulePath.set(true)`. In Gradle 7, it is turned on by default.

That's why it is not failing in 6.8.3. If you turn it on you get the same error in 6.8.3.

**Comment by jjohannes** [comment]
The setup in your reproducer looks complex. I think the problem is that you can't put the module info into the `kotlin` source folder because the Kotlin compiler can't deal with it. You need to put it in the `java` sources folder.

Maybe this example helps you: https://github.com/jjohannes/gradle-jpms-experiments/blob/master/module-kotlin/build.gradle.kts#L6-L9

**Comment by bjonnh** [comment]
Oh yeah sorry, regarding the **inferModulePath** I removed it to test if it was the problem in Gradle 7 as I saw it was not needed anymore. I'll put it back.

Regarding the module-info, it does not work if I put in in the java folder as in the repo you shared, it cannot find the net.nprod.demo package…

I pushed a "failure-module-in-java" branch with the settings you proposed.

**Comment by bjonnh** [comment]
@ljacomet I have the same error with 7.0-milestone-3

**Comment by jjohannes** [comment]
@bjonnh you need to adjust the patch argument with the right module ID (`demo` in your case):

```
tasks.compileJava {
    options.compilerArgs = listOf("--patch-module", "demo=${sourceSets.main.get().output.asPath}")
}
```

Then the sample still won't work because `smile.math` is NOT a module.

I see that you have been using `org.javamodularity.moduleplugin` before. Which works a bit different. Also IDEA works a bit different (recognising non-modules by deriving an automatic name from the Jar file name). 

You can use this to work with legacy libraries as modules: https://github.com/jjohannes/extra-java-module-info#how-to-use-this-plugin

So to clarify: there is not regression between Gradle 6.8.x and 7.0 that I can see here.

**Comment by bjonnh** [comment]
@jjohannes What I see is a project that worked with 6.8.3 doesn't start with 7.0… And I cannot find any change in parameters that would make it work with 7.0…  I'll push to a new branch the changes you proposed.  I did put the module-info.java into java sources and removed the linking of sources directories.

**Comment by bjonnh** [comment]
Please see the two branches :
- moved-module-to-java-working-6.8.3
- moved-module-to-java-not-working-7.0-milestone3

**Comment by bjonnh** [comment]
So that mean that I have to do 
````
java {
    modularity.inferModulePath.set(false)
}
````
For this program to work in 7.0. Not a regression, but that just something we may need to make users aware of when they transition to 7.0.

**Comment by bjonnh** [comment]
Thanks for walking with me through all of that, this really clarified how all of that works.

**Comment by bjonnh** [comment]
I'm trying https://github.com/jjohannes/extra-java-module-info#how-to-use-this-plugin right now see if that would made the transition easier.

**Comment by jjohannes** [comment]
> modularity.inferModulePath.set(false)
> For this program to work in 7.0. Not a regression, but that just something we may need to make users aware of when they transition to 7.0. 

Yes there is something in the release notes about this already.

But for your project it means that it never "really" worked. At least not without using "org.javamodularity.moduleplugin". Because all module information was simply ignored by Gradle.

You should be able to make it work with the `extra-java-module-info` plugin.

**Comment by bjonnh** [comment]
For me it worked because I was able to do ./gradlew run and the distributed jlink version was working as well for my end users. But yes it was not modular per se…

**Comment by bjonnh** [comment]
Ok your **extra-java-module-info** made it extremely easy, thanks a lot, that works perfectly now!

**Comment by bjonnh** [comment]
For anybody that got a similar issue and to not let you in the dark please check the branch [using-extra-java-module-info](https://github.com/bjonnh/2021_modules_unnamed_error/tree/using-extra-java-module-info) in the following repository: https://github.com/bjonnh/2021_modules_unnamed_error

**Comment by bjonnh** [comment]
@jjohannes  also moving the java compilation directory to kotlin is needed if you don't want to have to create empty packages in java: https://stackoverflow.com/questions/47657755/building-a-kotlin-java-9-project-with-gradle

I'm not sure there is any other alternative.

**Comment by bjonnh** [comment]
Another alternative someone sent me is to use:
````
tasks.withType<JavaCompile> {
    modularity.inferModulePath.set(true)
    options.compilerArgumentProviders.add(
        object : CommandLineArgumentProvider {
            @get:Optional
            @get:Classpath
            protected val compileKotlinOutputClasses = tasks.compileKotlin.flatMap { it.destinationDirectory }
            override fun asArguments() = listOf("--patch-module",
            "demo=${tasks.compileKotlin.get().destinationDir.absolutePath}")
        }
    )
}
````
