### ISSUE TITLE
Apply Version Catalog from project

### ISSUE THREAD

**Issue by little-fish** [gradle/gradle#18847]
I have a multi-project build with `version-catalog` project included. Applying version catalog from `project` doesn't work.
Documentation of [from(Object)](https://docs.gradle.org/current/javadoc/org/gradle/api/initialization/dsl/VersionCatalogBuilder.html#from-java.lang.Object-) methods says that _`dependencyNotation` parameter is any notation supported by [DependencyHandler](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/dsl/DependencyHandler.html)_.

### Expected Behavior
Version Catalog should be applied `from(project("..."))`.

### Current Behavior
`settings.gradle`
```groovy
```

### Context
We have multiple SCM repositories within our department. `core` for shared libraries and `impl` ones which depends on core.
Within the `core` library we want to have a `version-catalog` plugin which can be used within `core` repo itself and within `impl` repositories (with composition builds enabled/disabled).

### Your Environment
Gradle 7.2.

**Comment by little-fish** [comment]
Is there any workaround I can try?

**Comment by melix** [comment]
This isn't a bug but a consequence of the design. The `project` you want to import is in the same build. This means that itself, would have access to the catalog defined in settings. Therefore, it cannot participate in the definition of the catalog.

The workaround is easy: instead of using a `project` to declare your catalog, make it a distinct _build_ and include it.

**Comment by little-fish** [comment]
Thanks for the information.
I have tried your suggestion, but it didn't work for me. Or I do not know how to apply it:
`settings.gradle`:
```groovy
includeBuild("plugin-version-catalog")

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            from("_g_:plugin-version-catalog:_v_")
        }
    }
}
```
And I got this error:
```groovy
Could not resolve all artifacts for configuration 'incomingCatalogForLibs0'.
> Could not find g:a:v.
  Searched in the following locations:
...
Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```
So no dependency substitution happened. Am I missing something?

**Comment by melix** [comment]
mmm, no you're correct, I thought the substitution would automatically apply but it's not the case.

**Comment by little-fish** [comment]
So should I close this very issue and create new one describing the substitution problem with composite build?

**Comment by octylFractal** [comment]
I would appreciate it if you could simply edit this one to describe the correct issue with included builds, I was planning to have this same discussion and use this ticket if that bug existed.

**Comment by little-fish** [comment]
The ticket is updated. Thank you for your help.

**Comment by Phlegethon90** [comment]
@little-fish i got mine working. when you have multiple included builds, the order in the `settings.gradle.kts` does matter.

**Comment by jhansche** [comment]
A similar (but _probably_ different) issue occurs for a dependency defined inside a catalog, where the dependency's project is then included as a composite build:

```
[libraries]
my-lib = "group:my-lib:1.0.0"
```
```
api(libs.my.lib)
```
```
./gradlew assemble --include-build ../my-lib/
```
The expectation is that we will substitute the included `../my-lib` composite build, for the catalog-defined `libs.my.lib`. But that does not happen. Instead we get the same error, "Could not find group:my-lib:1.0.0", despite the composite build.

**Comment by skaluva** [comment]
Facing the same issue.. Im using gradle 7.2. Any workaround for this?

**Comment by skaluva** [comment]
@big-guy i see milestone for this is 8.0 RC1/ 8.1 RC1 which is way long. Is there any work around for now in 7.2 or above versions?

**Comment by rsicarelli** [comment]
After hours on this, I managed to make it work by renaming the published catalog artifact from `version-catalog` to `versioncatalog`:

Producer:
```kotlin
publishing {
    publications {
        register<MavenPublication>("catalog") {
            from(components["versionCatalog"])
            group = "com.org"
            artifactId = "versioncatalog"
            version = "1.0"
        }
    }

    repositories { ... }
}

```

Consumer:
```kotlin
dependencyResolutionManagement {
    repositories { .. }
    versionCatalogs {
        create("libs").from("com.org:versioncatalog:1.0")

        // fails with "Could not resolve all artifacts for configuration 'incomingCatalogForLibs0'." 
        // create("libs").from("com.org:version-catalog:1.0")
    }
```

**Comment by rsicarelli** [comment]
After hours on this, I managed to make it work by renaming the published catalog artifact from `version-catalog` to `versioncatalog`:

Producer:
```kotlin
//build.gradle.kts
publishing {
    publications {
        register<MavenPublication>("catalog") {
            from(components["versionCatalog"])
            group = "com.org"
            artifactId = "versioncatalog"
            version = "1.0"
        }
    }

    repositories { ... }
}

```

Consumer:
```kotlin
//settings.gradle.kts
dependencyResolutionManagement {
    repositories { .. }
    versionCatalogs {
        create("libs").from("com.org:versioncatalog:1.0")

        // fails with "Could not resolve all artifacts for configuration 'incomingCatalogForLibs0'." 
        // create("libs").from("com.org:version-catalog:1.0")
    }
```

**More context**
- The `artefactId` was declared as `version-catalog` for weeks and still works on some colleagues' machines (tested on the same branch)
- It stopped working for me when I published a new version to maven local. I changed the version to my local catalog, and once I tried to add the previous back, I got the error. 
- I manually deleted all catalogs from our maven registry (yolo), and published a new one using the changes, still same error.
- I tried deleted `.m2` (maven local) folder and `.gradle/caches`
- ✅ Publishing to maven local works with `version-catalog` as `artefactId`

**Comment by hakjac** [comment]
Tried with 8.0 RC2 but problem remain. Using includeBuild '<path-to-my-version-catalog>' does not substitute the one pointed out from settings.gradle

dependencyResolutionManagement {
    externalLibs {
      from("g.<my-version-catalog>.v")
    }
  }
}

**Comment by elect86** [comment]
Any news on this one?

I'm using the Setting API to generate the catalog:

```
class SciJavaCatalogPlugin : Plugin<Settings> {

    override fun apply(settings: Settings) {

        settings.dependencyResolutionManagement.versionCatalogs.addGeneratedCatalog() // this is generated
    }
}
```

but still no dependency substitution takes place..

**Comment by Vampire** [comment]
Same with 8.4

**Comment by cherni78** [comment]
I know its not the best solution, but works as a workaround, temporary! 
You can directly point to your toml file from your version catalog project for a composite build. 
Like so:
```
  versionCatalogs {
    libs {
      from(files("pathToVersionCatalogRepo/libs.versions.toml"))
    }
  }
```

**Comment by yuvaraj119** [comment]
still facing issue with [gradle version-8.5](https://github.com/gradle/gradle/issues/29369)

**Comment by yuvaraj119** [comment]
I see why it is happening. In module file the versionCatalogElements variant is missing.
`"variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "gradle-version-catalog-0.1.1-SNAPSHOT.toml",
          "url": "gradle-version-catalog-0.1.1-SNAPSHOT.toml",
          "size": 18559,
          "sha512": "xxxxx",
          "sha256": "xxxxxxx",
          "sha1": "xxxxxxxxxxxxx",
          "md5": "xxxxxxxxxxxxxxx"
        }
      ]
    }
  ]`
If in module file this is present when it will work.

Most of the time when i publish i see apiElements and runtimeElements variants not versionCatalogElements.
Not use which publish configuration make this possible to add `versionCatalogElements` variants

**Comment by Vampire** [comment]
You probably publish the `java` component instead of the `versionCatalog` component.

**Comment by yuvaraj119** [comment]
> You probably publish the `java` component instead of the `versionCatalog` component.

I tried with java it is same. With java the mavenPublishLocal is setting variant as `apiElements` and `runtimeElements`
expected is `versionCatalogElements` variant

I think the issue is with Jfrog publish which ignores the versionCatalog which holds `versionCatalogElements`  and publishs only publishMaven which holds `apiElements` and `runtimeElements`

Created a issue:
https://github.com/jfrog/artifactory-gradle-plugin/issues/113

Not sure it is gradle issue or jfrog plugin issue.

**Comment by Vampire** [comment]
> I tried with java it is same. With java the mavenPublishLocal is setting variant as apiElements and runtimeElements
expected is versionCatalogElements variant.

Sure, you did the opposite of what I said.

> I think the issue is with Jfrog publish

Quite possible, I often heard of strange things in their plugin.
Afaik, you can just use `maven-publish` and do not use their plugin.

**Comment by yuvaraj119** [comment]
> > I tried with java it is same. With java the mavenPublishLocal is setting variant as apiElements and runtimeElements
> > expected is versionCatalogElements variant.
> 
> Sure, you did the opposite of what I said.
> 
> > I think the issue is with Jfrog publish
> 
> Quite possible, I often heard of strange things in their plugin. Afaik, you can just use `maven-publish` and do not use their plugin.

Do you have any sample how can we use `maven-publish` to publish the artifacts in Jfrog artifactory.

**Comment by Vampire** [comment]
Nope, sorry, never used Artifactory, but I know that multiple people were pretty happy to just use `maven-publish` and get rid of the JFrog plugin. But if you have further questions to that, I suggest you ask somewhere else like the Forums, Slack, or StackOverflow, as it slightly gets a bit off-topic here. :-)

**Comment by vRallev** [comment]
This issue is still happening with Gradle 8.7. In my particular case the `versionCatalogElements` look correct:
```
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "abc-1.0.toml",
          "url": "abc-1.0.toml",
          "size": 355,
          "sha512": "44fff65d061c73135f5c8ca2c9c6c317dffbaa2a3d1f4451a8f0fb63da89ed02a7d8a29206bbe86575385c3f8c53470bbf91f1d9180f39d792590027d8a44ab0",
          "sha256": "b8234795c2a50e7a48c1dbf6243677f7b007f8178755c74ebed9e711b926bca4",
          "sha1": "5cb09fcb43dffc9bce0300c64087d4327feb59b9",
          "md5": "04f7cbf418055d2e78b94db18070fe9b"
        }
      ]
    }
  ]
```
The catalog is published like this:
```
apply plugin: 'version-catalog'
apply plugin: 'maven-publish'

catalog {
    versionCatalog {
        from files('../gradle/libs.versions.toml')
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.versionCatalog
        }
    }
}
```
Testing the same going through maven local works fine.

**Comment by sylwester-zielinski** [comment]
I have the same problem. I am using version-catalog in a separate project which is then deployed to Github Packages, but for development/testing I want to include it in the main app project using `includeBuild`.

`version-catalog` module in a `VersionCatalog` directory which has its' own `settings.gradle`:
```
group = "my.group"
version = project.findProperty("version") ?: "0.0.0"

catalog {
    versionCatalog {
        from(files("../gradle/libs.versions.toml"))
    }
}

publishing {
    val artifactId = "version-catalog"

    publications {
        create<MavenPublication>("libs") {
            from(components["versionCatalog"])

```

Then I'm trying to include it in the main app `settings.gradle` file:
```
includeBuild("../VersionCatalog")

...

dependencyResolutionManagement {
    versionCatalogs {
        val externalLibs by creating {
            from("my.group:version-catalog:1.0.0")
        }
```

I can see that the project has been added and I can browse it using IDE, but changes to version-catalog in `VersionCatalog` directory doesn't seem to override remotely deployed version catalog.

Should it work this way or there is some issue with this configuration?

**Comment by desiderantes** [comment]
I am affected by this bug. I used to be able to sidestep this issue by declaring a bogus substitution, like: 
```kotlin
includeBuild("catalog-build") {
  dependencySubstitution {
    substitute(module("com.package:whatever")).using(project(":"))
  }
}


dependencyResolutionManagement {
  versionCatalogs {
    create("libs") {
      from("com.package:whatever")
    }
  }
}
```
But this stopped working on 8.10

**Comment by 3ll3d00d** [comment]
came across this as part of changes required to upgrade to gradle 9 so this is still a problem with gradle 8.14.3, seems a big gap to leave for many years
