### ISSUE TITLE
Gradle complains about invalid tool chain - picking up the source package location - it should just ignore them

### ISSUE THREAD

**Issue by tkrah** [gradle/gradle#22921]
### Expected Behavior
Having a current debian / ubuntu LTS (22.x) distribution with e.g. the package:

openjdk-17-source
openjdk-11-source

installed.
This will result in the sources installed in:

/usr/lib/jvm/openjdk-17
/usr/lib/jvm/openjdk-11

It should ignore those directories for the toolchains and not complain about invalid JDKs - because I can't fix that, that's the valid package maintainers choice and gradle assumes something here which is wrong.

### Current Behavior
Gradle 7.6 complains about an invalid toolchain when running gradle tasks (where 7.5.1 does not do that):

```
Invalid Java installation found at '/usr/lib/jvm/openjdk-17' (Common Linux Locations). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.
Invalid Java installation found at '/usr/lib/jvm/openjdk-11' (Common Linux Locations). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.
```

But it just assumes that there should be a JDK there which of cause it is not and never was in the past years for the source packages.

gradle javaToolChains output:

```
 + Invalid toolchains
     + /usr/lib/jvm/openjdk-11
       | Error:              A problem occurred starting process 'command '/usr/lib/jvm/openjdk-11/bin/java''
       |     Caused by:      Could not start '/usr/lib/jvm/openjdk-11/bin/java'
       |     Caused by:      Cannot run program "/usr/lib/jvm/openjdk-11/bin/java" (in directory "/home/user/.gradle/.tmp/tmp-jvm15962250427739945112probe"): error=2, Datei oder Verzeichnis nicht gefunden
       |     Caused by:      error=2, Datei oder Verzeichnis nicht gefunden
     + /usr/lib/jvm/openjdk-17
       | Error:              A problem occurred starting process 'command '/usr/lib/jvm/openjdk-17/bin/java''
       |     Caused by:      Could not start '/usr/lib/jvm/openjdk-17/bin/java'
       |     Caused by:      Cannot run program "/usr/lib/jvm/openjdk-17/bin/java" (in directory "/home/user/.gradle/.tmp/tmp-jvm18195840401229065181probe"): error=2, Datei oder Verzeichnis nicht gefunden
       |     Caused by:      error=2, Datei oder Verzeichnis nicht gefunden

```

The correct toolchains which matches those are detected too:

```
 + Private Build JDK 17.0.5+8-Ubuntu-2ubuntu122.04
     | Location:           /usr/lib/jvm/java-17-openjdk-amd64
     | Language Version:   17
     | Vendor:             Private Build
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Current JVM

 + Ubuntu JDK 11.0.17+8-post-Ubuntu-1ubuntu222.04
     | Location:           /usr/lib/jvm/java-11-openjdk-amd64
     | Language Version:   11
     | Vendor:             Ubuntu
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Common Linux Locations


```
### Context
Just run gradle and have the packages:

openjdk-17-source
openjdk-11-source

installed on a current ubuntu LTS.

### Steps to Reproduce 
Just run:

gradle javaToolchains

**Comment by ljacomet** [comment]
Could you try with Gradle 7.5.1?

**Comment by tkrah** [comment]
7.5.1 does also complain in the "javaToolChains" task:

```
 + Invalid toolchains
     + /usr/lib/jvm/openjdk-17
       | Error:              A problem occurred starting process 'command '/usr/lib/jvm/openjdk-17/bin/java''
     + /usr/lib/jvm/openjdk-11
       | Error:              A problem occurred starting process 'command '/usr/lib/jvm/openjdk-11/bin/java''

```

but it does not complain when running other gradle tasks like 7.6 does:

```
Invalid Java installation found at '/usr/lib/jvm/openjdk-17' (Common Linux Locations). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.
Invalid Java installation found at '/usr/lib/jvm/openjdk-11' (Common Linux Locations). It will be re-checked in the next build. This might have performance impact if it keeps failing. Run the 'javaToolchains' task for more details.
```

Those are missing in 7.5.1 where 7.6 does show them.

**Comment by SimonMarquis** [comment]
Same issue here since we switched to Gradle 7.6

```
 > Task :javaToolchains

  + Options
      | Auto-detection:     Enabled
      | Auto-download:      Enabled

  + Debian JDK 11.0.16+8-post-Debian-1deb10u1
      | Location:           /usr/lib/jvm/java-11-openjdk-amd64
      | Language Version:   11
      | Vendor:             Debian
      | Architecture:       amd64
      | Is JDK:             true
      | Detected by:        Common Linux Locations

  + Invalid toolchains
      + /usr/lib/jvm/openjdk-11
        | Error:              A problem occurred starting process 'command '/usr/lib/jvm/openjdk-11/bin/java''
        |     Caused by:      Could not start '/usr/lib/jvm/openjdk-11/bin/java'
        |     Caused by:      Cannot run program "/usr/lib/jvm/openjdk-11/bin/java" (in directory "/home/zuul/.gradle/.tmp/tmp-jvm18249814244933718793probe"): error=2, No such file or directory
        |     Caused by:      error=2, No such file or directory
```

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.

----

The detection mechanism is too eager. We should only fail when we find a `java` executable but cannot probe the toolchain and simply ignore folders that don't contain a `java` executable.

**Comment by rybak** [comment]
For context, here are the files of the source package ([apt-file instructions](https://serverfault.com/a/96965/268447)):

```
$ apt-file list openjdk-17-source
openjdk-17-source: /usr/lib/jvm/openjdk-17/lib/src.zip
openjdk-17-source: /usr/share/doc/openjdk-17-source
```

and files of the actual JDK package:

```
$ apt-file list openjdk-17-jdk
openjdk-17-jdk: /usr/lib/jvm/java-17-openjdk-amd64/bin/jconsole
openjdk-17-jdk: /usr/lib/jvm/java-17-openjdk-amd64/include/jawt.h
openjdk-17-jdk: /usr/lib/jvm/java-17-openjdk-amd64/include/linux/jawt_md.h
openjdk-17-jdk: /usr/lib/jvm/java-17-openjdk-amd64/man/man1/jconsole.1.gz
openjdk-17-jdk: /usr/lib/jvm/openjdk-17/src.zip
openjdk-17-jdk: /usr/share/doc/openjdk-17-jdk
openjdk-17-jdk: /usr/share/doc/openjdk-17-jre-headless/test-amd64/check-hotspot-hotspot.log.gz
openjdk-17-jdk: /usr/share/doc/openjdk-17-jre-headless/test-amd64/check-jaxp-hotspot.log.gz
openjdk-17-jdk: /usr/share/doc/openjdk-17-jre-headless/test-amd64/check-jdk-hotspot.log.gz
openjdk-17-jdk: /usr/share/doc/openjdk-17-jre-headless/test-amd64/check-langtools-hotspot.log.gz
openjdk-17-jdk: /usr/share/doc/openjdk-17-jre-headless/test-amd64/failed_tests-hotspot.tar.gz
openjdk-17-jdk: /usr/share/doc/openjdk-17-jre-headless/test-amd64/jtreg-summary-hotspot.log.gz
openjdk-17-jdk: /usr/share/doc/openjdk-17-jre-headless/test-amd64/jtreg_output-hotspot.log
openjdk-17-jdk: /usr/share/doc/openjdk-17-jre-headless/test-amd64/jtreg_output-hotspot.log.gz
openjdk-17-jdk: /usr/share/doc/openjdk-17-jre-headless/test-amd64/jtreport-hotspot.tar.gz
```

And for `openjdk-8-*`:

```
$ apt-file list openjdk-8-source
openjdk-8-source: /usr/lib/jvm/openjdk-8/src.zip
openjdk-8-source: /usr/share/doc/openjdk-8-source
$ apt-file list openjdk-8-jdk
openjdk-8-jdk: /usr/lib/jvm/java-8-openjdk-amd64/bin/appletviewer
openjdk-8-jdk: /usr/lib/jvm/java-8-openjdk-amd64/bin/jconsole
openjdk-8-jdk: /usr/lib/jvm/java-8-openjdk-amd64/include/jawt.h
openjdk-8-jdk: /usr/lib/jvm/java-8-openjdk-amd64/include/linux/jawt_md.h
openjdk-8-jdk: /usr/lib/jvm/java-8-openjdk-amd64/lib/jconsole.jar
openjdk-8-jdk: /usr/lib/jvm/java-8-openjdk-amd64/man/ja_JP.UTF-8/man1/appletviewer.1.gz
openjdk-8-jdk: /usr/lib/jvm/java-8-openjdk-amd64/man/ja_JP.UTF-8/man1/jconsole.1.gz
openjdk-8-jdk: /usr/lib/jvm/java-8-openjdk-amd64/man/man1/appletviewer.1.gz
openjdk-8-jdk: /usr/lib/jvm/java-8-openjdk-amd64/man/man1/jconsole.1.gz
openjdk-8-jdk: /usr/share/doc/openjdk-8-jdk
openjdk-8-jdk: /usr/share/doc/openjdk-8-jre-headless/test-amd64/check-hotspot-hotspot.log.gz
openjdk-8-jdk: /usr/share/doc/openjdk-8-jre-headless/test-amd64/check-jdk-hotspot.log.gz
openjdk-8-jdk: /usr/share/doc/openjdk-8-jre-headless/test-amd64/check-langtools-hotspot.log.gz
openjdk-8-jdk: /usr/share/doc/openjdk-8-jre-headless/test-amd64/failed_tests-hotspot.tar.gz
openjdk-8-jdk: /usr/share/doc/openjdk-8-jre-headless/test-amd64/jtreg-summary-hotspot.log.gz
openjdk-8-jdk: /usr/share/doc/openjdk-8-jre-headless/test-amd64/jtreport-hotspot.tar.gz
openjdk-8-jdk: /usr/share/lintian/overrides/openjdk-8-jdk
```

The above is as of Ubuntu 22.04: https://packages.ubuntu.com/jammy/openjdk-17-jdk

**Comment by dmikurube** [comment]
Don't you have any plan to include this fix in the Gradle 7 series?

**Comment by ljacomet** [comment]
That is a possibility, filed #24439 for this

**Comment by dmikurube** [comment]
Thanks! Great to hear that.

**Comment by tomwhoiscontrary** [comment]
I'd just like to add a note that i'm seeing a variant of this, using Gradle 8.0.2, on Fedora 36, because there is some weird cruft in the system JDK installations. Running `gradle javaToolChains` produces output including many entries like this:

```
 + Invalid toolchains
     + /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64
       | Error:              A problem occurred starting process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64/bin/java''
       |     Caused by:      Could not start '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64/bin/java'
       |     Caused by:      Cannot run program "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64/bin/java" (in directory "/home/twic/.gradle/.tmp/tmp-jvm6186714809953911816probe"): error=2, No such file or directory
       |     Caused by:      error=2, No such file or directory
     + /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181.b15-6.fc28.x86_64
       | Error:              A problem occurred starting process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181.b15-6.fc28.x86_64/bin/java''
       |     Caused by:      Could not start '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181.b15-6.fc28.x86_64/bin/java'
       |     Caused by:      Cannot run program "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181.b15-6.fc28.x86_64/bin/java" (in directory "/home/twic/.gradle/.tmp/tmp-jvm12767888901630257395probe"): error=2, No such file or directory
       |     Caused by:      error=2, No such file or directory
     + /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-4.b10.fc27.x86_64
       | Error:              A problem occurred starting process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-4.b10.fc27.x86_64/bin/java''
       |     Caused by:      Could not start '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-4.b10.fc27.x86_64/bin/java'
       |     Caused by:      Cannot run program "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-4.b10.fc27.x86_64/bin/java" (in directory "/home/twic/.gradle/.tmp/tmp-jvm15554442380472419319probe"): error=2, No such file or directory
       |     Caused by:      error=2, No such file or directory
```

Looking at that first location:

```
$ find /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64 | sort
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64/jre
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64/jre/lib
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64/jre/lib/ext
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64/jre/lib/security
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64/jre/lib/security/local_policy.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc28.x86_64/jre/lib/security/US_export_policy.jar
```

The rpm database says no package owns those files. So i'm guessing that at some point in the past, this was the JDK installed by the package manager, then some process caused those policy jars to appear, then the JDK got upgraded and this package was removed, but because these files are not part of the package, they were left, meaning this husk of a JDK was left, which is now confusing Gradle.

I can upgrade this project to Gradle 8.1+, at which point i expect this problem will disappear. I am leaving this comment so that if someone else has this problem and googles with the error message, they may find this explanation.

**Comment by SerErris** [comment]
I can reproduce the same error with openjdk-19 and Ubuntu 22.04

~/java/JAPR02$ gradle --version

------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 12:31:26 UTC
Revision:     1cf537a851c635c364a4214885f8b9798051175b

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          19.0.2 (Private Build 19.0.2+7-Ubuntu-0ubuntu322.04)
OS:           Linux 5.15.0-72-generic amd64

:~/java/JAPR02$ gradle test
Path for java installation '/usr/lib/jvm/openjdk-19' (Common Linux Locations) does not contain a java executable

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 up-to-date

Gradle has been installed via the github download (not the ubuntu version) and openjdk-19 has been installed via direct .deb download from java.org

**Comment by frost13it** [comment]
> printed once per daemon

> Gradle no longer list those as errors

Are you describing behavior of some future version of Gradle?
This is not the case on 8.1.1 or 8.2-rc-2, unfortunately

**Comment by timothyfroehlich** [comment]
I've just had a user get in touch with me because they thought there was an error here.

**Comment by project-rozu** [comment]
commenting out this fixed it for me

**Comment by Gerald1973** [comment]
Hello try this:
org.gradle.java.installations.auto-detect=false

Gradle will use your configured JAVA_HOME directory or the one crated in the gradle.properties file.  For example:
org.gradle.java.home=/home/myusername/programmation/tools/java/OpenJDK8U-jdk_x64_linux_hotspot_8u392b08/jdk8u392-b08

**Comment by talesborn** [comment]
I have the same problem!
Still no solution?

**Comment by twbecker** [comment]
I'm up to 4 JDKs on my system and have to see this spam every time I do a build. Why can't this just be logged at a slightly lower level?

**Comment by pkubowicz** [comment]
> Hello try this:
> org.gradle.java.installations.auto-detect=false

This is not a solution! It's like saying that a solution to Gradle crashing is uninstalling Gradle. Or that if the incremental compilation does not work for you, there is no problem, just disable the incremental compilation and you should be happy.

I agree with comments above: **this issue should be re-opened as it is not fixed at all**. The was probably not a single moment it worked on Ubuntu.

Auto-detection is *broken* for all Ubuntu based (or even all Debian-based) systems. In those systems, /usr/lib/jvm/openjdk-11 **will never contain a Java executable** (because of the way apt-get packages of Java are prepared by system maintainers). It's **bad logic in Gradle** as it's incorrect on those systems to try to find a Java executable where it never was and probably will never be.

**Comment by atom888888** [comment]
I am still seeing this issue also on Gradle 8.5 on Ubuntu 22.04.4 LTS

**Comment by AnonymoScoot** [comment]
Problem still persists here, but I managed to make a workaround by including a symbolic link to the actual folder that has the java binaries using command `sudo ln -s /usr/lib/jvm/java-21-openjdk-amd64/bin /usr/lib/jvm/openjdk-21`.

**Comment by ljacomet** [comment]
Can someone share the output of `./gradlew javaToolchains` from an affected system with a Gradle version > 8.1?

Ideally, two versions of it:
* One where a daemon is started
* Then one where a daemon is re-used

**Comment by pkubowicz** [comment]
> I am still seeing this issue also on Gradle 8.5

Can you try 8.8, where a fix was made? See https://github.com/gradle/gradle/issues/29062#issuecomment-2110142263

**Comment by ljacomet** [comment]
Thanks for the reminder! 🤦 

Please, if you still see an issue, upgrade to Gradle 8.8 and share the output you are seeing with and without daemon reuse.

**Comment by tomwhoiscontrary** [comment]
These messages no longer appear with 8.9:

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 8.9
------------------------------------------------------------

Build time:    2024-07-11 14:37:41 UTC
Revision:      d536ef36a19186ccc596d8817123e5445f30fef8

Kotlin:        1.9.23
Groovy:        3.0.21
Ant:           Apache Ant(TM) version 1.10.13 compiled on January 4 2023
Launcher JVM:  17.0.6 (Azul Systems, Inc. 17.0.6+10-LTS)
Daemon JVM:    /home/twic/.asdf/installs/java/zulu-17.40.19 (no JDK specified, using current Java home)
OS:            Linux 6.9.7-200.fc40.x86_64 amd64

$ ./gradlew clean build
Starting a Gradle Daemon (subsequent builds will be faster)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 17s
8 actionable tasks: 8 executed
$ ./gradlew clean build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 8s
8 actionable tasks: 8 executed
```
