### ISSUE TITLE
Refreshing changing dependencies doesn't work correctly

### ISSUE THREAD

**Issue by meonlol** [gradle/gradle#2317]
For our company we have a large, multi-repository, multi-module gradle setup. The code is separated in multiple smaller but interdependent artifacts which are downloaded from, and published to, our artifactory-server. For active development, all artifacts are versioned with "-SNAPSHOT".
This setup works pretty well, but only if we run `--refresh-dependencies` often to force refreshing of our SNAPSHOTs. This makes building unreliable from IDE's and also forces needles refreshes of non-changing artifacts.

### Expected Behavior
If artifacts are suffixed with "-SNAPSHOT" they should be marked changing. Artifacts that are marked changing should be refreshed every single time if `resolutionsStrategy.cacheChangingModulesFor 0, 'seconds'` is set. Both for direct, and for transitive dependencies.

### Current Behavior
Even though dependencies are downloaded some of the time, they are not refreshed reliably. It is hard to test what causes the dependencies to download or to be marked as up-to-date, but I think they are not marked as 'changing' correctly. The only thing I found in the logs after much experimentation was the following when using `--refresh-dependencies`:

```
[DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.IvyXmlModuleDescriptorParser] post 1.3 ivy file: using exact as default matcher
[DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] Metadata file found for module 'com.company:some-artifact:master-SNAPSHOT' in repository 'ARTIFACTORY_REPO'.
[DEBUG] [org.gradle.api.internal.artifacts.ivyservice.modulecache.DefaultModuleMetaDataCache] Recording module descriptor in cache: com.company:some-artifact:master-SNAPSHOT [changing = false]
[DEBUG] [org.gradle.api.internal.file.delete.Deleter] Deleting /home/USER_NAME/.gradle/caches/modules-2/metadata-2.23/descriptors/com.company/some-artifact/master-SNAPSHOT/5a53c5d0c22379b62e7ea108d68c191d/descriptor.bin
[DEBUG] [org.gradle.api.internal.file.delete.Deleter] Deleting /home/USER_NAME/.gradle/caches/modules-2/metadata-2.23/descriptors/com.company/some-artifact/master-SNAPSHOT/5a53c5d0c22379b62e7ea108d68c191d/descriptor.bin.fslck
```
Company details are obviously changed but the interesting part was the `[changing = false]` part, which is logged out by gradle at [this line](https://github.com/gradle/gradle/blob/ee9895d2abf3d14539f2916dc54b01f9716cb02d/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/DefaultModuleMetaDataCache.java#L99). This suggests that somewhere the `changing` property is not correctly forwarded.

### Setup to Reproduce
```
▾ repo1/
    ▾ module-one/
        build.gradle
    build.gradle
▾ repo2/
    ▾ module-two/
        build.gradle
    build.gradle
```

And in module-two the following setup.
```
def version = "master-SNAPSHOT" //Actually provided by a custom plugin
dependencies {
	compile("com.company:module-one:${version}")
}
```
The problem occurs when module-one is already in cache, but has been changed and republished to the same location with the same version name. The changed version is not re-downloaded.

### Environment
Reproducible on Ubuntu (14 and 16) and on Windows 7. Version output:
```
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)
OS:           Linux 3.11.0-26-generic amd64
```

### What I've tried
I've tried setting the `changing` property manually, both for transitive and direct dependencies, but this did not change anything.
```
    configurations.all { config ->
        resolutionStrategy {
            cacheChangingModulesFor 0, 'seconds'
            cacheDynamicVersionsFor 0, 'seconds'
        }
        incoming.beforeResolve {
            allDependencies*.each { dep ->
                if ( dep.getVersion()?.endsWith( '-SNAPSHOT' ) ) {
                    if ( dep.metaClass.respondsTo( 'setChanging', Boolean ) ) {
                        dep.setChanging( true )
                    }
                }
            }
        }
        afterEvaluate {
            if (config.state != org.gradle.api.artifacts.Configuration.State.UNRESOLVED) {
                throw new GradleException("ERROR: [...]")
            }
            allDependencies*.each { dep ->
                if (dep instanceof ExternalModuleDependency) {
                    if (dep.version.endsWith("-SNAPSHOT")) {
                        dep.setChanging(true)
                    } else if (dep.group.equals('de.esolutions')) {
                        logger.warn("WARNING: Custom version used for eso project '${dep.group}:${dep.name}:${dep.version}' in $config. Don't forget to fix this before comitting.")
                    }
                }
            }
        }
```

**Comment by bmuschko** [comment]
Do you configure `cacheChangingModulesFor` and `cacheDynamicVersionsFor` for all projects or the subproject that need it by using `allprojects` or `subprojects`? Just putting the logic into the root build script of your multi-project build won't do.

**Comment by bmuschko** [comment]
@meonlol Did you get your issue resolved in the meantime?

**Comment by meonlol** [comment]
Sorry, I'm very busy at the moment.
I do apply it for all projects, which makes it so weird.

I realize that it will be hard to reproduce, so I will try to setup a demo project to isolate the problem away from our setup as soon as possible.

**Comment by meonlol** [comment]
Okay, so I reproduced the Bug:
https://github.com/meonlol/bug-refresh-dependencies

The dependency-graph is like this:
```
project:proj-module
\---  sdk:sdk-module
      \--- sdk:sdk-module-api
```

`sdk-module` depends on `sdk-module-api`

So when I make a change in the Interface in `sdk-module-api`, publish it to artifactory, and run `./gradlew build -I ../init.gradle` from `project`, I expect it to download the changed jar for sdk-module-api automatically, as all artifacts are marked `-SNAPSHOT`, but it does not refresh without `--refresh-dependencies`.

I've tried to explicitly set the incoming dependencies to `changing` using the `init.gradle` script, but is seems to have no effect.

**Comment by bschelberg** [comment]
We've just come across this problem also - although I don't think it's because of SNAPSHOT dependencies being marked as changing = false. What we do see is that, even though we've overridden the default cache expiry using cacheChangingModulesFor, the cache is only "expired" after 24 hours. I've done some debugging of this, and it appears to be because even though all the Configurations defined by the gradle script have an extra moduleCacheRule and artifactCacheRule with the expiry age that we've specified in the build script, when it comes time to do the actual resolving, the Configuration used is a detachedConfiguration (not sure what that is), created in the MavenPomResolver (from the dependency-management-plugin). Detached configurations are created with the DefaultConfigurationContainer.detachedConfiguration() method, and they don't have the extra moduleCacheRule or artifactCacheRule on the DefaultCachePolicy in the ResolutionStrategy.

I hope that makes some kind of sense to someone with a better knowledge of Gradle than myself.

**Comment by meonlol** [comment]
I've just tested it and the bug is still present in Gradle 4.3.1.
This bug forces us to --refresh-dependencies on all our builds, and as our project grows our build times also increase, which is getting to a point where it starts becoming a real problem for our developers.

Could someone please look in to this?

**Comment by bmuschko** [comment]
Thanks for providing a sample project. I am going to have a look in the coming days. General observation: You use the Maven SNAPSHOT syntax though you are publishing and consuming to an Ivy repository. What's the backstory here? Why don't you set up a Maven repository if that's the concept you'd like to use.

**Comment by meonlol** [comment]
Well, when we started on this project we decided to make our build system compatible with our old projects, which use Ant, and since Ivy was built for Ant we decided go with that.  
Later we wanted to have our internal artifacts represent the tips of our branches, for which we decided to use the `-SNAPSHOT` notation as we figured the standardized notation would mark the artifacts as changing automatically.

**Comment by bigdaz** [comment]
A module with a `*-SNAPSHOT` version _coming from a Maven repository_ will be considered changing by default. **If you're using an Ivy repository, this rule doesn't apply**, which means you'll need to tell Gradle to consider these modules as changing.

Note that the code in your example `init.gradle` will not apply to transitive dependencies. You're using `configuration.allDependencies {}` which applies to direct dependencies declared in the configuration or any parent configurations, but not transitive dependencies.

So you have a few options:
1. Stop using `SNAPSHOT` modules, and instead publish each SNAPSHOT with a unique version and use a version range selector to get the latest one.
2. Switch to using a Maven repository, for which Gradle will automatically consider `SNAPSHOT` to mean 'changing'.
3. Tell Gradle to consider all `-SNAPSHOT` dependencies as changing, something like this:
```
dependencies {
    components {
         all { ComponentMetadataDetails details ->
             if (details.id.version.endsWith('-SNAPSHOT')) {
                  details.changing = true
             }
         }
    }
}
```

**Comment by meonlol** [comment]
We've tried option 3, as you can see in the code under "What I've tried" in my initial comment, and it doesn't work. That's the problem.

**Comment by meonlol** [comment]
I could not get your suggestion to work. This is still a problem, that is consistently reproducible in the repo I've built for it:
https://github.com/meonlol/bug-refresh-dependencies

I will try and see if we can migrate to a maven repo as a workaround.

**Comment by bigdaz** [comment]
Sorry if I wasn't clear: **Gradle does not treat SNAPSHOT dependencies in Ivy repositories as changing**. This isn't a bug: because `SNAPSHOT` modules are a Maven concept we decided long ago to only treat these as changing when they are found in a Maven repository.

**Comment by bigdaz** [comment]
To get the `components` rule working, try adding it to https://github.com/meonlol/bug-refresh-dependencies/blob/master/project/proj-module/build.gradle. It might be worth adding a `println details.id` before the `if` block in the rule to see if any components are being loaded by the rule.

Something like this:

```
dependencies {
    compile("com.bug.refresh.dependencies:sdk-module:${version}")

    components {
         all { ComponentMetadataDetails details ->
             println details.id
             if (details.id.version.endsWith('-SNAPSHOT')) {
                  details.changing = true
             }
         }
    }
}
```
