### ISSUE TITLE
Gradle 7.4 fails on multi release jar's with JDK 19 code

### ISSUE THREAD

**Issue by yanivkr** [gradle/gradle#24390]
When `com.fasterxml.jackson.core:jackson-core:2.15.0-rc1` is in the buildscript dependencies it fails to write locks.
### Expected Behavior
Build should succeed 
### Current Behavior
Build fails with the error 
```
./gradlew build                                                                                                                                                           

 FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /Users/<redacted>/.gradle/caches/jars-9/c94f549fdaad0dab4fb786ae7d97e150/jackson-core-2.15.0-rc1.jar.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 569ms
```

### Steps to Reproduce 
Clone [this](https://github.com/yanivkr/gradle-jackson-bug) repo and run `./gradlew build`

### Your Environment

Build scan URL:
cannot provide build scan

### Additional notes:
- Version `2.15.0-rc1` of `jackson-core` introduces a multi-release jar [[link to release notes](https://github.com/FasterXML/jackson-core/blob/2.15/release-notes/VERSION-2.x#L32-L33)], which is likely the reason why this error occurs on this particular version and not earlier versions.
- This bug does not reproduce in Gradle version 7.6.1

**Comment by pjfanning** [comment]
@yanivkr could you rename the issue that issue is associated with Gradle's instrumenting of multi-release jars? The current title makes it more likely that noone will look at the issue - that they might think it is user error as opposed to an underlying issue that might still affect gradle. A multi-release jar with support for Java 20 classes may still be a problem in latest Gradle releases - even if they appear to have fixed the issue with Java 19 classes.

**Comment by cowtowncoder** [comment]
@yanivkr Also... I know this is asking for a lot but just in case it was possible, it'd be great to know if possible earlier Gradle versions might not have the issue (or, conversely, do have). Any additional datapoints pre-7.4 would be useful.
Or if anyone else could help here it'd be much appreciated of course :)

**Comment by yanivkr** [comment]
@pjfanning Renamed the issue.
@cowtowncoder According to gradle doc Java 19 support was only added at Gradle 7.6.

Can the change be backported to Gradle 7.4.X?

**Comment by pjfanning** [comment]
I created a forum topic to see if I could interest any Gradle folk in this issue. https://discuss.gradle.org/t/is-there-any-way-to-skip-gradle-instrumenting-classpath-file-transformer/45213

**Comment by cowtowncoder** [comment]
@yanivkr Right, I get that support for JDK 19 bytecode was only added then. What I was/am wondering is whether earlier Gradle versions might have avoided the issue by not trying to process bytecode in question (sometimes earlier tool versions happen to work, not by design but by lucky omission).

**Comment by jjohannes** [comment]
The title/description here sounds like **Gradle can't build anything that depends on multi release jar's with JDK 19 code**
(and this seems to cause some 'concerns').

This is **not true (!)**

The error appears when you use such a Jar in **Gradle Plugins** (or custom build logic). 

For example:
````
buildscript { // <- Here we talk about extending Gradle itself!
    dependencies {
        classpath 'com.fasterxml.jackson.core:jackson-core:2.15.0-rc1'
    }
}
````

It seems that this is already fixed in 7.6. This is kind of a normal situation for code that _extends Gradle itself_. I don't think there is anything left to do.

It does not mean that there is a problem with building Java/Kotlin/Android/etc Applications or Libraries with such Jars. I assume that this works fine (and these are probably like 99% of the cases where e.g. Jackson is used in Gradle builds).

For example:
```
plugins {
    id 'application'
}

dependencies {
   implementation 'com.fasterxml.jackson.core:jackson-core:2.15.0-rc1'
}
```

**Comment by pjfanning** [comment]
Thanks @jjohannes - that lowers the importance of the issue for Jackson users

**Comment by Toldry** [comment]
@jjohannes this bug critically impacted my organization. 

Each of our Java projects use our internally developed Gradle plugin, which somehow got `com.fasterxml.jackson.core:jackson-core:2.15.0-rc1 ` transitively leaked into its' dependencies, and since our projects use Gradle version less than 7.6.1, then it caused all builds to fail.

For now as a workaround we added the following code section to the `init.gradle` in all developer machines and build services:

```
initscript {
    // Temporary workaround
    gradle.allprojects {
        buildscript {
            configurations.all {
                resolutionStrategy.force 'com.fasterxml.jackson.core:jackson-core:2.14.2'
                resolutionStrategy.force 'com.fasterxml.jackson.core:jackson-annotations:2.14.2'
                resolutionStrategy.force 'com.fasterxml.jackson.core:jackson-databind:2.14.2'
                resolutionStrategy.force 'com.fasterxml.jackson:jackson-bom:2.14.2'
                resolutionStrategy.force 'com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.14.2'
                resolutionStrategy.force 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.14.2'
                resolutionStrategy.force 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.14.2'
                resolutionStrategy.force 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.2'
                resolutionStrategy.force 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.14.2'
                resolutionStrategy.force 'com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.14.2'
            }
        }
    }}
```

I'm working on upgrading all our projects to Gradle 7.6.1, including our internally developed Gradle plugin. This is not a trivial upgrade because several of our plugin's dependencies themselves are incompatible with Gradle 7.6.1

**Comment by cowtowncoder** [comment]
@Toldry sorry to hear about all this trouble, and thank you for sharing it. This is very unfortunate.

**Comment by ghale** [comment]
My understanding is that this can be an issue even on Gradle 7.6.1.  Although that version supports running Gradle on JDK19, it still uses ASM 9.2, which only supports bytecode up to JDK18.  So instrumentation of JDK19 classes can still fail on 7.6.1.  Gradle 8.1 has updated ASM to 9.4 as part of the JDK20 support, but we should consider updating ASM for Gradle 7.x as well.

**Comment by ljacomet** [comment]
Done through #25050

**Comment by nivsa** [comment]
This issue now happens with the new version of jackson-core:2.16.1 which uses JDK 21

**Comment by mlopatkin** [comment]
> This issue now happens with the new version of jackson-core:2.16.1 which uses JDK 21

The issue is resolved as of Gradle 8.4. Please follow #27156 for a potential backport to 7.6.x line.

**Comment by JiaqiFlora** [comment]
I have 2 projects (gradle 7.5), the dependency tree uses jackson-core-2.15.3. But one of them works, another one has the issue as above. why? Thank you in advance!
