### ISSUE TITLE
Gradle should use a supported keystore type for encryption key

### ISSUE THREAD

**Issue by xnox** [gradle/gradle#31377]
### Expected Behavior

Currently

```
platforms/core-configuration/encryption-services/src/main/kotlin/org/gradle/internal/encryption/impl/KeyStoreKeySource.kt:        const val KEYSTORE_TYPE = "pkcs12"
```

Is a constant. However, different java installs may not have, or block, using pkcs12 keystore format. For example on my java install I must use `bcfks` and in some other cases an `nssdb` keystore might need to be used.

Is it possible to add a runtime configuration to specify a keystore type, or possibly automatically detect it? (i.e. if highest priority security provider is BC-FJA or SunPKCS11 then use bcfks or nssdb keystores)

### Current Behavior (optional)

build fails unable to open/create pkcs12 keystore

### Context

```
gradle init --type java-application --dsl kotlin --test-framework junit-jupiter --package my.project --project-name my-project --no-split-project --incubating --configuration-cache-problems warn --java-version 17 && gradle build
```

fails

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by xnox** [comment]
Hm, something changed between gradle 8.10.2 and 8.11.0 as previously it was working fine with my restricted JDK configuration using BC-FJA providers in FIPS approved only mode, but now it fails with:

> Could not open Gradle Configuration Cache keystore (/root/.gradle/caches/8.11-20241111000000+0000/cc-keystore).
> java.security.KeyStoreException: Key protection algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: getPBEAlgorithmParameters failed: PBEWithHmacSHA256AndAES_256 AlgorithmParameters not available

And i cannot tell if my configuration is missing some settings; or if something changed in gradle that is trying to bypass JDK configuration (or makes up own configuration?!) which is breaking the builds.

**Comment by abstratt** [comment]
> but now it fails with:

@xnox Can you please provide a stacktrace for the error above (by using Gradle's `-s` option), and not only the exception message?

**Comment by abstratt** [comment]
@xnox Also, it seems providers will support only some key protection algorithms. Gradle uses "AES/CTR/NoPadding".

**Comment by xnox** [comment]
> [@xnox](https://github.com/xnox) Also, it seems providers will support only some key protection algorithms. Gradle uses "AES/CTR/NoPadding".

THANK YOU!!!!! THIS NOW MAKES SO MUCH MORE SENSE!

Btw i have been pinning to gradle prior to this change.

Also can we use something modern, like AES-GCM => not sure which java versions support that though. I will go and check if AES/CTR/NoPadding is available to me, or blocked for other reasons.

**Comment by xnox** [comment]
oh, i see there is gcm support, not too sure how to opt into it, but will try.

**Comment by xnox** [comment]
I will get back to you with more info later in the week.

**Comment by abstratt** [comment]
Fixed by #34096

**Comment by abstratt** [comment]
@xnox Would you be able to try a [nightly build](https://gradle.org/nightly/) and see if Gradle honors the custom keystore type configuration?

**Comment by xnox** [comment]
I have tested 9.1.0-20250726001724+0000

```
$ gradle init --type java-application --dsl kotlin --test-framework junit-jupiter --package my.project --project-name my-project --no-split-project --incubating --java-version 21
$ gradle build --stacktrace
....
BUILD SUCCESSFUL in 44s
7 actionable tasks: 7 executed
Configuration cache entry stored.
```

Doing gradle init and build now works. It also last worked with 8.10.2 release, but not with gradle 8.11 or higher (let me double check).

Will this fix be backported to 8.x series? Or should I attempt to backport it myself?

as 8.14 still fails for me.

```
/home/build/test-8.14 # gradle init --type java-application --dsl kotlin --te
st-framework junit-jupiter --package my.project --project-name my-project --n
o-split-project --incubating --java-version 21
NOTE: Picked up JDK_JAVA_OPTIONS: --module-path=/usr/share/java/bouncycastle-fips -Djavax.net.ssl.trustStoreType=FIPS --add-exports=java.base/sun.security.internal.spec=ALL-UNNAMED --add-exports=java.base/sun.security.provider=ALL-UNNAMED
Picked up JAVA_TOOL_OPTIONS: --module-path=/usr/share/java/bouncycastle-fips

Welcome to Gradle 8.14.3-20250717000000+0000!

Here are the highlights of this release:
 - Java 24 support
 - GraalVM Native Image toolchain selection
 - Enhancements to test reporting
 - Build Authoring improvements

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :init
Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.3-20250717000000+0000/samples/sample_building_java_applications.html

BUILD SUCCESSFUL in 8s
1 actionable task: 1 executed

/home/build/test-8.14 # gradle build --stacktrace
NOTE: Picked up JDK_JAVA_OPTIONS: --module-path=/usr/share/java/bouncycastle-fips -Djavax.net.ssl.trustStoreType=FIPS --add-exports=java.base/sun.security.internal.spec=ALL-UNNAMED --add-exports=java.base/sun.security.provider=ALL-UNNAMED
Picked up JAVA_TOOL_OPTIONS: --module-path=/usr/share/java/bouncycastle-fips

FAILURE: Build failed with an exception.

* What went wrong:
Could not open Gradle Configuration Cache keystore (/root/.gradle/caches/8.14.3-20250717000000+0000/cc-keystore).
> java.security.KeyStoreException: Key protection algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: getPBEAlgorithmParameters failed: PBEWithHmacSHA256AndAES_256 AlgorithmParameters not available

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.cache.CacheOpenException: Could not open Gradle Configuration Cache keystore (/root/.gradle/caches/8.14.3-20250717000000+0000/cc-keystore).
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:77)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:36)
        at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:102)
        at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:63)
        at org.gradle.cache.internal.DefaultCacheBuilder.open(DefaultCacheBuilder.java:79)
        at org.gradle.internal.encryption.impl.KeyStoreKeySource.getKey(KeyStoreKeySource.kt:102)
        at org.gradle.internal.encryption.impl.DefaultEncryptionService.secretKeyFrom(DefaultEncryptionService.kt:71)
        at org.gradle.internal.encryption.impl.DefaultEncryptionService.produceSecretKey(DefaultEncryptionService.kt:61)
        at org.gradle.internal.encryption.impl.DefaultEncryptionService.access$produceSecretKey(DefaultEncryptionService.kt:37)
        at org.gradle.internal.encryption.impl.DefaultEncryptionService$secretKey$2.invoke(DefaultEncryptionService.kt:54)
        at org.gradle.internal.encryption.impl.DefaultEncryptionService$secretKey$2.invoke(DefaultEncryptionService.kt:53)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.gradle.internal.encryption.impl.DefaultEncryptionService.getSecretKey(DefaultEncryptionService.kt:53)
        at org.gradle.internal.encryption.impl.DefaultEncryptionService.isEncrypting(DefaultEncryptionService.kt:91)
        at org.gradle.internal.cc.impl.ConfigurationCacheKey.putCacheKeyComponents(ConfigurationCacheKey.kt:79)
        at org.gradle.internal.cc.impl.ConfigurationCacheKey.access$putCacheKeyComponents(ConfigurationCacheKey.kt:32)
        at org.gradle.internal.cc.impl.ConfigurationCacheKey$string$2.invoke(ConfigurationCacheKey.kt:42)
        at org.gradle.internal.cc.impl.ConfigurationCacheKey$string$2.invoke(ConfigurationCacheKey.kt:40)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at org.gradle.internal.cc.impl.ConfigurationCacheKey.getString(ConfigurationCacheKey.kt:40)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache$storeDelegate$1.invoke(DefaultConfigurationCache.kt:120)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache$storeDelegate$1.invoke(DefaultConfigurationCache.kt:120)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache.getStore(DefaultConfigurationCache.kt:123)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache.loadCandidateEntries(DefaultConfigurationCache.kt:487)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache.access$loadCandidateEntries(DefaultConfigurationCache.kt:78)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache$checkFingerprint$1.invoke(DefaultConfigurationCache.kt:454)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache$checkFingerprint$1.invoke(DefaultConfigurationCache.kt:453)
        at org.gradle.configurationcache.ConfigurationCacheBuildOperationsKt$withFingerprintCheckOperations$1.call(ConfigurationCacheBuildOperations.kt:136)
        at org.gradle.configurationcache.ConfigurationCacheBuildOperationsKt$withFingerprintCheckOperations$1.call(ConfigurationCacheBuildOperations.kt:130)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:210)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:205)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:54)
        at org.gradle.configurationcache.ConfigurationCacheBuildOperationsKt.withFingerprintCheckOperations(ConfigurationCacheBuildOperations.kt:130)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache.checkFingerprint(DefaultConfigurationCache.kt:453)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache.determineCacheAction(DefaultConfigurationCache.kt:387)
        at org.gradle.internal.cc.impl.DefaultConfigurationCache.initializeCacheEntry(DefaultConfigurationCache.kt:188)
        at org.gradle.internal.cc.impl.ConfigurationCacheBuildTreeLifecycleControllerFactory.createRootBuildController(ConfigurationCacheBuildTreeLifecycleControllerFactory.kt:67)
        at org.gradle.composite.internal.DefaultRootBuildState.<init>(DefaultRootBuildState.java:77)
        at org.gradle.composite.internal.BuildStateFactory.createRootBuild(BuildStateFactory.java:68)
        at org.gradle.composite.internal.DefaultIncludedBuildRegistry.createRootBuild(DefaultIncludedBuildRegistry.java:88)
        at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:53)
        at org.gradle.internal.buildtree.InitDeprecationLoggingActionExecutor.execute(InitDeprecationLoggingActionExecutor.java:62)
        at org.gradle.internal.buildtree.InitProblems.execute(InitProblems.java:36)
        at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
        at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:71)
        at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:60)
        at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:71)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$2.call(RunAsBuildOperationBuildActionExecutor.java:67)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$2.call(RunAsBuildOperationBuildActionExecutor.java:63)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:210)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:205)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:67)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:60)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:167)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:60)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:54)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:63)
        at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)
        at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
        at org.gradle.tooling.internal.provider.continuous.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:110)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
        at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
        at org.gradle.internal.buildprocess.execution.BuildSessionLifecycleBuildActionExecutor$ActionImpl.apply(BuildSessionLifecycleBuildActionExecutor.java:92)
        at org.gradle.internal.buildprocess.execution.BuildSessionLifecycleBuildActionExecutor$ActionImpl.apply(BuildSessionLifecycleBuildActionExecutor.java:80)
        at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:73)
        at org.gradle.internal.buildprocess.execution.BuildSessionLifecycleBuildActionExecutor.execute(BuildSessionLifecycleBuildActionExecutor.java:62)
        at org.gradle.internal.buildprocess.execution.BuildSessionLifecycleBuildActionExecutor.execute(BuildSessionLifecycleBuildActionExecutor.java:41)
        at org.gradle.internal.buildprocess.execution.StartParamsValidatingActionExecutor.execute(StartParamsValidatingActionExecutor.java:64)
        at org.gradle.internal.buildprocess.execution.StartParamsValidatingActionExecutor.execute(StartParamsValidatingActionExecutor.java:32)
        at org.gradle.internal.buildprocess.execution.SessionFailureReportingActionExecutor.execute(SessionFailureReportingActionExecutor.java:51)
        at org.gradle.internal.buildprocess.execution.SessionFailureReportingActionExecutor.execute(SessionFailureReportingActionExecutor.java:39)
        at org.gradle.internal.buildprocess.execution.SetupLoggingActionExecutor.execute(SetupLoggingActionExecutor.java:47)
        at org.gradle.internal.buildprocess.execution.SetupLoggingActionExecutor.execute(SetupLoggingActionExecutor.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:70)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.lambda$execute$0(ForwardClientInput.java:40)
        at org.gradle.internal.daemon.clientinput.ClientInputForwarder.forwardInput(ClientInputForwarder.java:80)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:64)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator.lambda$runCommand$0(DaemonStateCoordinator.java:321)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
Caused by: org.gradle.internal.UncheckedException: java.security.KeyStoreException: Key protection algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: getPBEAlgorithmParameters failed: PBEWithHmacSHA256AndAES_256 AlgorithmParameters not available
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:69)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:42)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:234)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:221)
        at org.gradle.cache.internal.FixedSharedModeCrossProcessCacheAccess.open(FixedSharedModeCrossProcessCacheAccess.java:83)
        at org.gradle.cache.internal.DefaultCacheCoordinator.lambda$open$0(DefaultCacheCoordinator.java:133)
        at org.gradle.cache.internal.DefaultCacheCoordinator.withOwnershipNow(DefaultCacheCoordinator.java:202)
        at org.gradle.cache.internal.DefaultCacheCoordinator.open(DefaultCacheCoordinator.java:128)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:75)
        ... 104 more
Caused by: java.security.KeyStoreException: Key protection algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: getPBEAlgorithmParameters failed: PBEWithHmacSHA256AndAES_256 AlgorithmParameters not available
        at org.gradle.internal.encryption.impl.KeyStoreKeySource.generateKey(KeyStoreKeySource.kt:84)
        at org.gradle.internal.encryption.impl.KeyStoreKeySource.createKeyStoreAndGenerateKey(KeyStoreKeySource.kt:53)
        at org.gradle.internal.encryption.impl.KeyStoreKeySource.access$createKeyStoreAndGenerateKey(KeyStoreKeySource.kt:29)
        at org.gradle.internal.encryption.impl.KeyStoreKeySource$getKey$1.accept(KeyStoreKeySource.kt:101)
        at org.gradle.internal.encryption.impl.KeyStoreKeySource$getKey$1.accept(KeyStoreKeySource.kt:100)
        at org.gradle.cache.internal.DefaultPersistentDirectoryCache$Initializer.initialize(DefaultPersistentDirectoryCache.java:115)
        at org.gradle.cache.internal.FixedSharedModeCrossProcessCacheAccess$1.run(FixedSharedModeCrossProcessCacheAccess.java:86)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:231)
        ... 110 more
Caused by: java.security.UnrecoverableKeyException: Encrypt Private Key failed: getPBEAlgorithmParameters failed: PBEWithHmacSHA256AndAES_256 AlgorithmParameters not available
        ... 118 more
Caused by: java.io.IOException: getPBEAlgorithmParameters failed: PBEWithHmacSHA256AndAES_256 AlgorithmParameters not available
        ... 118 more
Caused by: java.security.NoSuchAlgorithmException: PBEWithHmacSHA256AndAES_256 AlgorithmParameters not available
        ... 118 more


BUILD FAILED in 2s
/home/build/test-8.14 # gradle --version
NOTE: Picked up JDK_JAVA_OPTIONS: --module-path=/usr/share/java/bouncycastle-fips -Djavax.net.ssl.trustStoreType=FIPS --add-exports=java.base/sun.security.internal.spec=ALL-UNNAMED --add-exports=java.base/sun.security.provider=ALL-UNNAMED
Picked up JAVA_TOOL_OPTIONS: --module-path=/usr/share/java/bouncycastle-fips

------------------------------------------------------------
Gradle 8.14.3-20250717000000+0000
------------------------------------------------------------

Build time:    2025-07-17 00:00:00 UTC
Revision:      e5ee1df3d88b8ca3a8074787a94f373e3090e1db

Kotlin:        2.0.21
Groovy:        3.0.24
Ant:           Apache Ant(TM) version 1.10.15 compiled on August 25 2024
Launcher JVM:  21.0.8 (wolfi 21.0.8+-wolfi-r1)
Daemon JVM:    /usr/lib/jvm/java-21-openjdk (no JDK specified, using current Java home)
OS:            Linux 6.15.7-zabbly+ amd64
```

**Comment by xnox** [comment]
For my needs

```
-        const val KEYSTORE_TYPE = "pkcs12"
+        val KEYSTORE_TYPE = KeyStore.getDefaultType()
```

is enough of a backport of this feature to upgrade to latest 8.14 build;

and I am happy this is fixed more comprehensively in mainline / 9.x releases (including support for weak default keystores with automatic upgrade to better ones).

Thank you!

**Comment by xnox** [comment]
Oh, release notes PR is still open.
