### ISSUE TITLE
Fix BuildTree sciped ObjectFactory fileResolver

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#32018]
`ObjectFactory` created in `BuildTree` scope has `FilePropertyFactory` and `FileCollectionFactory` that are using `IdentityFileResolver` instead of `BaseDirFileResolver` .
That means that setting relative paths for `DirectoryProperty/RegularFileProperty` doesn't work for objects created with this `ObjectFactory`. One example is exec provider in `build.gradle` script, e.g. after the migration this fails:
```
// build.gradle
def execProvider = providers.exec {
    workingDir = new File("test/bla")
}
```
with:
```
Caused by: java.lang.UnsupportedOperationException: Cannot convert relative path test/bla to an absolute file.
```

We should probably use correct FileResolver here.

![Image](https://github.com/user-attachments/assets/04a7db6e-4e82-432b-9728-006ba881b4ef)

**Comment by mlopatkin** [comment]
We should have a unified approach to resolving relative paths everywhere they can appear. I.e. every path in the project scope is resolved against the project dir, every path in settings scope against the settings dir, and so on.

For this particular issue, let's have ObjectFactory and ProviderFactory in every scope with a proper FileResolver.

**Comment by alllex** [comment]
I think we should separate the cases we want to fix.

Specifically for this snippet from above:
```groovy
// build.gradle
def execProvider = providers.exec {
    workingDir = new File("test/bla")
}
```

The problem is not that the `ObjectFactory` used somewhere inside `exec` is build-tree scoped and lacks a base to resolve relative files. The problem is that the `exec` called in the project scope doesn't resolve files relative to the current project. In other words, it uses the wrong instance of `ObjectFactory`.

**Comment by asodja** [comment]
It seems like `providers.exec` issue can be solved separately from this one. And this one looks like a bigger issue. I created https://github.com/gradle/gradle/issues/33133 to solve `Providers.exec` issue and I will target that for 9.0. And this one can be solved later in 9.x.

**Comment by oehme** [comment]
The problem isn't just relative paths, but the fact that `providers.exec {}` doesn't use the working dir of the current project by default, which is pretty confusing, because you got it from `project.providers`. All other `exec`-like things run in the projec dir by default. `Providers.exec` runs in the root dir.

**Comment by asodja** [comment]
We said we won't do this, but rather do https://github.com/gradle/gradle/issues/33278. Lets look at this before Gradle 10
