### ISSUE TITLE
Gradle should fail if task dependencies are mutated after the task graph is ready

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#4848]
The upgrade to Gradle 4.6 using AGP 3.0.1 caused some release builds to break in unpredictable ways. Upon investigation, we found the root cause is the configuration of certain projects during the execution phase (probably caused by https://github.com/gradle/gradle/pull/3998).

The issue shows up in builds that use a lint task in AGP, since lint resolves all configurations for the project, which causes unresolved configurations to configure projects that may not have been configured during the configuration phase. This is particularly bad in release builds, since they include a `lintVital` task by default.

One way to repro is by adding a dependency on a project exclusively to the `androidTestImplementation` configuration - when building an apk, this project will only be configured when running the lint task.

And the reason why this introduces instability in AGP 3.0.1, 3.1 and 3.2 is the `TaskInputHelper` class, which is meant to disable certain file collections during the configuration phase in order to delay resolution:

```public class TaskInputHelper {

    private static AtomicBoolean bypassSupplier = new AtomicBoolean(true);

    public static void disableBypass() {
        bypassSupplier.set(false);
    }

    public static void enableBypass() {
        bypassSupplier.set(true);
    }
```

`enableBypass` is called when the plugin is applied (which assumes that the application of the plugin happens during the configuration phase) and `disableBypass` is called in a `TaskExecutionGraphListener` (which will never run if already in the execution phase). As a result, the configuration of a project during the execution phase calls `enableBypass` and never calls `disableBypass`, which causes all sort of unintended consequences in tasks that run after that point.

In my view, this is a bug in Gradle, since it's modifying the task graph after the graph is declared ready - however, it's an artifact of configuration on demand so I'm wondering whether it's expected? In practice, this is causing instability of Android builds, so it should be addressed either in Gradle or AGP.

**Comment by bigdaz** [comment]
Thanks for the detailed report and analysis. We'll take a look, but can't simply revert the change you referenced, since that fixed another regression, ....

In the meantime, can you run your builds without configure-on-demand?

**Comment by ducrohet** [comment]
We should probably remove our bypass, but it's going to be in 3.2, which means 3.0.x and 3.1 are broken with 4.6 and CoD. We will document this.

**Comment by blindpirate** [comment]
@bigdaz Will this be solved in `4.7RC1`?

**Comment by bigdaz** [comment]
@blindpirate Very unlikely. I've change the target milestone to 4.8-rc-1.

**Comment by cwoodwar6** [comment]
For us, one of the unpredictable results of this was that the dex files were not being placed into the release APK. Setting either `checkReleaseBuilds false` for lint or `org.gradle.configureondemand=false` solved it.

**Comment by technoir3** [comment]
@gradle-team can this be prioritized? Many Android projects will be stuck on 4.5.1 until this is fixed.
CoD is a per-project user setting in AS so asking every developer to disable it for every project is not a good option.

**Comment by oehme** [comment]
This needs to be fixed in the Android plugin. Project's being configured at execution time can happen when they are not properly declared as dependencies. E.g. it seems that the lint task is not declaring that it wants to resolve all configurations.

We can certainly improve diagnostics here, i.e. fail more eagerly when someone attempts to change task dependencies later on.

**Comment by ducrohet** [comment]
This is already fixed in 3.2

**Comment by cesar1000** [comment]
@ducrohet is the lint task fixed to declare all dependencies though? That sounds like the right fix here. Also, it would help enable up-to-date checks and cacheability of the lint tasks :)

**Comment by ducrohet** [comment]
That's a somewhat unrelated issues, but yes we need to do this still (AFAIK)

**Comment by cesar1000** [comment]
Not really unrelated though: lint is looping through all configurations, causing every configuration that wasn't resolved during the configuration phase to be resolved during the execution phase. This may cause a delayed configuration of some of the projects if CoD is enabled, which may alter the build in arbitrary ways. If gradle enables stricter checks (as suggested by the new title of this issue), the lint task may fail the build.

**Comment by ducrohet** [comment]
The resolved configuration is something different compared to the inputs. Declaring the inputs will not help configuring the sub-projects on time, nor should it.
The issue here is that, at exec time, lint will query sub-projects for a model (similar to studio sync)which trigger their configuration. This is something we need to improve somehow.

The right fix is not to attempt to delay things until after configuration since our detection for where we are (before/after config) does not account for all use cases. This is what is fixed in 3.2

**Comment by ljacomet** [comment]
No changes are planned on the Gradle side for this, so closing.

If you feel this is still an issue to be addressed on the Gradle side, please provide more input so that the topic can be accounted for in prioritization.
