### ISSUE TITLE
Welcome message doesn't check quiet flag

### ISSUE THREAD

**Issue by mkordas** [gradle/gradle#5213]
New feature introduced in #4766 prints release info even if `-q` flag is used.

### Expected Behavior
When run first time after update to 4.7 `gradlew -q build` should print release info.

### Current Behavior
Release info is printed despite quiet mode.

### Context
I use `gradlew -q printVersion` to print current project version. Adding release info broke my builds.

**Comment by marcphilipp** [comment]
@eriwen @bmuschko  What's the intended behavior?

**Comment by bmuschko** [comment]
@marcphilipp At the moment the messaging is not routed through the Gradle logger.

**Comment by oehme** [comment]
It broke his build because now it doesn't just print the version, but the release notes too.

**Comment by ratemyduck** [comment]
This hit us too. Our scripts are using the system out to to resolve some properties which are computed with gradle

**Comment by marcphilipp** [comment]
Indeed, that should work as a workaround:

```
$ ./gradlew --quiet -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false --version

------------------------------------------------------------
Gradle 4.8-rc-2
------------------------------------------------------------

Build time:   2018-05-24 09:28:21 UTC
Revision:     0b1824635622a85b201776fc1245b6a40f4a5b22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.13.4 x86_64
```

vs.

```
$ ./gradlew --quiet --version

Welcome to Gradle 4.8-rc-2!

Here are the highlights of this release:
 - Dependency locking
 - Maven Publish and Ivy Publish plugins improved and marked stable
 - Incremental annotation processing enhancements
 - APIs to configure tasks at creation time

For more details see https://docs.gradle.org/4.8-rc-2/release-notes.html


------------------------------------------------------------
Gradle 4.8-rc-2
------------------------------------------------------------

Build time:   2018-05-24 09:28:21 UTC
Revision:     0b1824635622a85b201776fc1245b6a40f4a5b22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.13.4 x86_64
```

**Comment by orende** [comment]
In the future, _please don't do something like this again_. For containerized environments that reinstall gradle every time they're run, this causes the release notes to be displayed every time the gradle command is run. A lot of automated builds broke because of this.

**Comment by lacasseio** [comment]
Microsoft compilers use `-nologo` to suppress startup banner. We could have something similar like `--no-banner`. However, fixing the display in quiet mode should be the most important here.

**Comment by Xerus2000** [comment]
The workaround didn't work for me using gradlew with Gradle 10, the welcome message appears every time in Travis... Command: `./gradlew deploy -q -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false` yields:
```
Welcome to Gradle 4.10!
Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC3
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block
For more details see https://docs.gradle.org/4.10/release-notes.html
```

**Comment by marcphilipp** [comment]
Are you sure your Travis job does not call Gradle multiple times?

**Comment by stefan-huettemann** [comment]
The "Welcome" message is still present in Gradle 4.10.2.

_Please_ make `gradle -q` really quiet!

This has cost us valuable time and resources.

**Comment by ajermakovics** [comment]
The internal flag workaround didn't work for me so instead I'm using this:
```
touch ~/.gradle/notifications/4.8.1/release-features.rendered
```

**Comment by arakelian** [comment]
Respectfully, marketing / welcome messages should not be output in quiet mode.  

Imagine if utilities like cat, find, gcc, gpg, etc., suddenly introduced "welcome" messages when you ran them in the console:
- "GCC 7 now uses LRA by default!", 
- "GPG now supports Elliptical Curve Cryptography!"

Gradle's fundamental utility is as a command line tool for executing builds.  IMHO, It should be scriptable, and should respect norms (like quiet mode) that are well established.

**Comment by arakelian** [comment]
Thank you

**Comment by thomas-k-huber** [comment]
Thanks for finding the flag, @ratemyduck. Adding it as a sysprop in the project's gradle.properties file silences the message without touching the wrapper, script, pipeline or build containers; worked for 4.9 and 4.10.2.
```
systemProp.org.gradle.internal.launcher.welcomeMessageEnabled=false
```

**Comment by manuel-plavsic** [comment]
> Thanks for finding the flag, @ratemyduck. Adding it as a sysprop in the project's gradle.properties file silences the message without touching the wrapper, script, pipeline or build containers; worked for 4.9 and 4.10.2.
> 
> ```
> systemProp.org.gradle.internal.launcher.welcomeMessageEnabled=false
> ```

I am new with Grails. What do I have to do (e.g. which dependencies should I import) to make this work?

**Comment by britter** [comment]
> I am new with Grails. What do I have to do (e.g. which dependencies should I import) to make this work?

@manuel-plavsic what are you trying to do? The issue has been fixed in Gradle 5.3.

**Comment by manuel-plavsic** [comment]
I would love to hide the welcome message, which in my case gets printed every time when I run build.gradle

**Comment by britter** [comment]
@manuel-plavsic are you using Gradle 5.3 and are you passing the `-q` flag? If so, please open a new issue and report this as a bug following the corresponding issue template.

**Comment by jpbottinelli** [comment]
This is still an issue in 5.6 and our CI is failing even when passing the -q argument. Is there any real way of solving this? Thanks

**Comment by landsman** [comment]
Still present in 6.7.1.

**Comment by britter** [comment]
@gradle/core does anybody have capacity to look into this?
