### ISSUE TITLE
performance problems with java-library on a large project on Windows

### ISSUE THREAD

**Issue by diacone** [gradle/gradle#6784]
### Expected Behavior
at least similar performance to java plugin

### Current Behavior
60% slowdown for java compile tasks (from 12 minutes to 20 minutes)

### Context
Just by switching from java to java-library plugin the performance dropped significantly on Windows machines. We had to switch back to java plugin because majority of our developers runs Windows.

### Steps to Reproduce (for bugs)
Run two builds one with java and one with java-library plugin

### Your Environment
* Gradle 4.9
* Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
* Windows 10
* large multi-project build (~250 projects)
* large projects (biggest sub-projects >= 20k source files)

**Comment by big-guy** [comment]
Hi @diacone 

Could you provide more details (which version of Java and Gradle)?

The java and java-library plugins are nearly the same.  They share the same task implementation, so it would be very unusual for the tasks to behave differently.

Could you share [build scans](https://scans.gradle.com/) for before/after the switch?

Thanks!

**Comment by diacone** [comment]
We use version 4.9 (can't use 4.10(.1) until some issues are fixed) and unfortunately, no, I can't provide build scan result.

I can send you (personally) generated profile (--profile) and/or flight recording if you wish.

More notes:
* it takes very long time even before javac is spawned
* javac itself is much (much!) slower when source set folders are used instead of jar files

**Comment by diacone** [comment]
Anything new regarding this problem? java-library is near to unsuable on Windows machines...

**Comment by hdecarne** [comment]
Same here:

With java plugin:
BUILD SUCCESSFUL in 5m 22s
819 actionable tasks: 818 executed, 1 up-to-date

With java-library plugin:
BUILD SUCCESSFUL in 34m 4s
819 actionable tasks: 818 executed, 1 up-to-date

Gradle version:
Gradle 4.10.2
Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Windows 7 6.1 amd64

**Comment by jjohannes** [comment]
We finally took a closer look at this issue. It seems to be pretty clear that this is caused by Gradle's fie snapshotting applied on a (very very) large amount of class files on the classpath. I was able to reproduce this with a test project, but only after adding a substantial amount of classes (~25k) and making sure the classpath is large by using only `compile` / `api` dependencies.

If the project is smaller, or the single subprojects are more isolated during compilation (i.e. use mostly `implementation` dependencies). The issue does not seem to appear and the current `java-library` behavior might also be faster on Windows.

We have a solution that allows you to turn on the behavior of using _jars_ instead on _class folders_ for compilation in the `java-library` plugin by setting a system property. In my tests, this showed an equal performance for the `java` and `java-library` plugin for the test project. 

@diacone @hdecarne, if you are still following this and are still interested in a solution, I would appreciate if you could give the proposed solution a spin on your projects. From the numbers you reported, the problem seems to be even worse there than in my test project. I created a _branch nightly_ that includes the feature. You can find it here: https://services.gradle.org/distributions-snapshots/gradle-5.6-branch-compile_classpath_packaging-20190626185628+0000-bin.zip

To turn it on, you need to set the the following system property:
`org.gradle.java.compile-classpath-packaging=true`.
You can do that, for example, by calling gradle with `-Dorg.gradle.java.compile-classpath-packaging=true` or by adding `systemProp.org.gradle.java.compile-classpath-packaging=true` to your _gradle.properties_.
Any kind of feedback on this is highly appreciated. Thanks a lot!

**Comment by hdecarne** [comment]
@jjohannes thanks for working on that topic. I have checked with you branch nightly and the results are:

With java plugin (default build options)
BUILD SUCCESSFUL in 21m 38s
1239 actionable tasks: 1238 executed, 1 up-to-date

With java-library plugin (default build options)
BUILD SUCCESSFUL in 1h 7m 0s
1226 actionable tasks: 1136 executed, 90 up-to-date (there was a build issue, thats why this not a complete rebuild; actually the build time is even higher)

With java-library plugin (-Dorg.gradle.java.compile-classpath-packaging=true)
BUILD SUCCESSFUL in 13m 9s
1239 actionable tasks: 1238 executed, 1 up-to-date

Looks very good to me.

**Comment by jjohannes** [comment]
Thanks @hdecarne! That looks indeed good and confirms our own observations. If things work out as planned, this will go into `5.6`.

**Comment by ljacomet** [comment]
Fix has been merged, all done

**Comment by davidfra** [comment]
This improvement vastly increased the performance of our build on Windows 10.

It only has one drawback: When using the Gradle-Daemon, I cannot run ``gradlew clean`` any more, because the jars that were created on the previous build are still loaded by the daemon.

We are using the gradle OSGi plugin, BTW, not the java-library plugin. But I am not sure if this changes anything.

**Comment by jjohannes** [comment]
@davidfra this should not happen. All files a build opened should also be released again before the build ends. It sounds like a potential bug that was only revealed now.

Which `OSGi` plugin are you using? Note that the `OSGi` plugin bundled with Gradle is deprecated and will not longer be part of Gradle soon. If you are using that, have you tried using https://plugins.gradle.org/plugin/biz.aQute.bnd instead?

**Comment by davidfra** [comment]
@jjohannes Yes, we are still using the deprecated bundled OSGi plugin, but we have already planned to update. AFAIK, this was not straight forward, but I will try to have a look soon and report back my experiance.

If no one else had troubles with `gradlew clean` with this new setting, it must be due to the OSGi plugin. It makes troubles in other situations, too.

**Comment by davidfra** [comment]
@jjohannes 
I managed to migrate to the new OSGi plugin, which was quite some work as there is no really good documentation or guide.
However, this did not solve the whole problem with the clean, but I found a solution for that, too.

There was one sub module which contained classes but also contained other sub modules. This bundle was the one producing the error. I moved all the classes to another sub module, so that the problematic module now only contains sub modules but no classes of its own.
Now the build works without problems.

Thanks for for this improvement.

**Comment by sebersole** [comment]
FWIW, this causes problems building multi-module projects when a project defining an auto Java 9 module name (project-a) and another project (project-b) defines an explicit Java module that `requires` project-a.

These auto names are defined via entry in the jar's manifest.  However, this plugin disables building that Jar.  The end result is that the Java 9 module for project-a is never found in project-b by module name.

There is a system setting to disable this under the premise that you'd only want to do that if you use Windows.  However, my situation is (imo) a bug and atm there is no way to work-around this.

Should I create a new bug report?

https://discuss.gradle.org/t/disable-using-classes-instead-of-jar-for-compilation/39835

**Comment by sebersole** [comment]
> there is no way to work-around this

Well every developer could define `org.gradle.java.compile-classpath-packaging=true` for their local env and we could change the many CI jobs we have...

So technically there is a workaround - just not a particularly practical one

**Comment by jjohannes** [comment]
@sebersole this is indeed the wrong solution for the problem you are describing.

There are other ways to let Gradle know that you need the Jar for a certain reason. It should work out of the box for Java Modules. `java-library` should automatically go into a mode where it uses the Jars if you are building a Module.

In Gradle 7, this should work out of the box as soon as you have a `module-info.java` in the main source set of the project that is a module.

In Gradle 6, you have to turn module support on by:

``` 
java.modularity.inferModulePath.set(true)
```

Do you have some custom setup to build your module? And if, can you change it to use Gradle's built-in module support?

**Comment by sebersole** [comment]
project-a does not define a `module-info.java`, it uses "auto module naming".  project-b does in fact define a `module-info.java` but the problem is that Gradle does not understand that it needs the jar from project-a.

At least, that's sure what it seems like.

I'm not sure what you mean by "custom setup to build your module".

**Comment by jjohannes** [comment]
Sorry I was not clear. If `project-b` has a module file, it should request and get the jar for **all** its dependencies. The details of `project-a` should not matter.

Can you maybe share a reproducer of the problem?

**Comment by sebersole** [comment]
I am trying to boil that down.  The real build is the Hibernate ORM build which is far more complex.  Though perhaps that complexity is part of the problem...

**Comment by jjohannes** [comment]
If you can point me at the problematic module/projects in the Hibernate ORM repository, I can have a direct look.

**Comment by sebersole** [comment]
It is a branch I have locally.  I can push it to my repo if that would help.  

I just want to use the newer dependency configurations (api, implementation, etc).

**Comment by jjohannes** [comment]
Whatever works best for you. If I have something to reproduce what you are seeing, I can help you better.

**Comment by sebersole** [comment]
@jjohannes I created a PR illustrating the problem.  I isolated as best I could the changes related to the plugin change.  Running that build with Java 11 will fail unless `org.gradle.java.compile-classpath-packaging=true` is specified.

Thanks for looking!

**Comment by sebersole** [comment]
I guess the PR link helps :P

https://github.com/hibernate/hibernate-orm/pull/3965

**Comment by jjohannes** [comment]
@sebersole you are not using Gradle's built-in module support that was introduced in 6.4. But the `java-modules` 3rd party plugin. You should switch to the built-in support and then you will not have the issue.

https://github.com/hibernate/hibernate-orm/blob/16cf75219a0e1e7738d1e807d7fd9ba75e23fcbc/hibernate-integrationtest-java-modules/hibernate-integrationtest-java-modules.gradle#L23-L25

First replace the above with:
```
java.modularity.inferModulePath = true
```

Then you should move all the code of the `hibernate-integrationtest-java-modules` project to the `src/test` folder (from `src/main`). Otherwise, Gradle would not recognise it as "one module" and your tests will not run "as module".

I also think the current setup is a bit flawed, because of how the `java-modules` plugin just opens some things via command line args in the background.

I needed to add this to the `module-info.java` (which is now in _src/test_):

```
requires java.sql;

opens org.hibernate.orm.integrationtest.java.module.test;
requires junit;
```

You also need to upgrade JUnit to `4.13.2` because `4.12` does not define an automatic module name.

Then it works and you make sure that your "test module" has all information in the "module-info.java".

**Comment by sebersole** [comment]
Wow @jjohannes a lot ot unpack there :)

I'll stop the discussion here so as to not muddy up this issue, but wanted to say thank you so much for researching this.  It would have taken me forever to find that, if I found it at all.

**Comment by jjohannes** [comment]
No problem. Fell free to ping on your PR on the Hibernate repo, if this does still not work.
