### ISSUE TITLE
Gradle wrapper fails to escape arguments with nested quotes

### ISSUE THREAD

**Issue by delego-wlritchi** [gradle/gradle#865]
When passed an argument with nested quotes, such as `'-DFOO="bar < baz"'`, the Unix Gradle wrapper script from version 3.2 fails because it tries to pipe input from the `baz` file - the argument is not correctly escaped.

### Expected Behavior
`./gradlew '-DFOO="bar < baz"'` should escape its arguments correctly when executing Gradle

### Current Behavior
`./gradlew '-DFOO="bar < baz"'` fails with `No such file or directory` (assuming the `baz` file does not exist)

### Context
This pattern of nested quotes is produced by Jenkins' Gradle integration, and it will always contain a `<` when triggered by Gerrit integration. Our continuous integration is broken by this bug.

### Steps to Reproduce (for bugs)
* Clone https://github.com/delego-wlritchi/gradle-wrapper-bug
* Run `./gradlew '-DFOO="bar < baz"' hello`

### Your Environment
* Gradle Version: 3.2
* Last worked correctly in: 3.1
* Operating System: Arch Linux 64-bit
* JVM version: OpenJDK 1.8.0_112

**Comment by bmuschko** [comment]
@delego-wlritchi Thanks for reporting. I think the field `Last worked correctly in` in your report is probably not correct. Was the last working version 3.1?

**Comment by delego-wlritchi** [comment]
Indeed it was; edited accordingly.

**Comment by jjohannes** [comment]
Thanks for reporting. This is a regression with argument escaping in start scripts.

I pushed a fix to `master`: https://github.com/gradle/gradle/commit/a171b72b0973ace7b1f9c17551654c0de1ca49e2

**Comment by wolfs** [comment]
@delego-wlritchi Could you try applying [this](https://github.com/gradle/gradle/commit/a171b72b0973ace7b1f9c17551654c0de1ca49e2#diff-36ffbd2ea7085cf19547193a7faf30c8) to your `gradlew` script and see if this fixes the issue for you?

**Comment by delego-wlritchi** [comment]
Confirmed, that patch fixes the issue. Thanks for the quick response!

**Comment by eriwen** [comment]
Reopened until we deliver a fix for this in Gradle 3.3

**Comment by gerhardol** [comment]
As I end up here on web searches: This problem still exists in Cygwin, double quotes are removed.
The 'for arg in "$@" ; do' snippet breaks the argument handling, the save() fix due to this PR is insufficient.
